CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE NVARCHAR2(100) NOT NULL ENABLE,
    EMAIL NVARCHAR2(100) UNIQUE NOT NULL ENABLE, 
    TELEFONO NVARCHAR2(100) NOT NULL ENABLE,
    CALLE NVARCHAR2(100) NOT NULL ENABLE,
    COLONIA NVARCHAR2(100) NOT NULL ENABLE,
    NUMERO NVARCHAR2(20) DEFAULT ('S/N'),
    DELETE_AT TIMESTAMP NULL
);



INSERT INTO CLIENTES (NOMBRE, EMAIL, TELEFONO, CALLE, COLONIA)
    VALUES ('JESUS', 'jesus@hotmail.com', '123456879', 'ENRIQUE', 'SEGOVIANO');

DROP TABLE CLIENTEs;

DROP TABLE PRODUCTO;

CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE NVARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION NVARCHAR2(100),
    PRECIO NUMBER NOT NULL,
    STOCK NUMBER NOT NULL,
    FECHA_EMPAQUE DATE DEFAULT CURRENT_TIMESTAMP,
    UNIDAD_VENTA NVARCHAR2(20),
    DELETE_AT TIMESTAMP NULL,
    CONSTRAINT CK_UnidadVenta 
        CHECK (UNIDAD_VENTA IN ('PIEZA', 'DOCENA', 'BANDEJA', 'CAJA'))
        
);

INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, PRECIO, STOCK, UNIDAD_VENTA)
    VALUES('HUEVO BLANCO', 'HUEVO BLANCO DE GALLINA LIBRE', 8, 120, 'PIEZA');
COMMIT;

SELECT * FROM PRODUCTOS;

DROP TABLE PEDIDO;

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER GENERATED ALWAYS AS IDENTITY,
    CLIENTE_ID NUMBER NOT NULL,
    FECHA_PEDIDO DATE DEFAULT CURRENT_TIMESTAMP,
    FECHA_ENTREGA DATE NOT NULL,
    TOTAL NUMBER,
    ESTADO NVARCHAR2(20),
     DELETE_AT TIMESTAMP NULL,
    CONSTRAINT CK_Estado
        CHECK(ESTADO IN ('PENDIENTE', 'PROCESANDO', 'ENTREGADO', 'CANCELADO'))
);

INSERT INTO PEDIDOS(CLIENTE_ID, FECHA_ENTREGA, TOTAL, ESTADO)
    VALUES(1, TO_DATE('17/02/2026'), 231, 'PENDIENTE');
    
SELECT * FROM PEDIDOS;

CREATE TABLE DETALLE_PEDIDO(
    ID_DETALLE_PEDIDO NUMBER GENERATED ALWAYS AS IDENTITY,
    PEDIDO_ID NUMBER NOT NULL,
    PRODUCTO_ID NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER NOT NULL,
    PRECIO_TOTAL NUMBER NOT NULL,
    DELETE_AT TIMESTAMP NULL
);

INSERT INTO DETALLE_PEDIDO(PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL),

CREATE TABLE PAGOS(
    ID_PAGO NUMBER GENERATED ALWAYS AS IDENTITY,
    PEDIDO_ID NUMBER NOT NULL,
    METODO NVARCHAR2(10),
    FECHA_PAGO DATE DEFAULT CURRENT_TIMESTAMP,
    MONTO NUMBER NOT NULL,
    DELETE_AT TIMESTAMP NULL
);