--1.CREAR UNA TABLA ALUMNO(ID, NOMBRE, APELLIDO, EDAD, CARRERA, PROMEDIO, GENERO(M o F)
CREATE TABLE ALUMNO(
    ID_ALUMNO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    PROMEDIO NUMBER,
    GENERO NVARCHAR2(100)

);

--VAN A INSERTAR POR LO MENOS 7 VALORES
INSERT INTO ALUMNO VALUES(1,'DANIELA','GOMEZ',36,'ADMINISTRACION',9.0,'F');
INSERT INTO ALUMNO VALUES(2,'SEBASTIAN','FLORES',70,'SISTEMAS',9.5, 'M');
INSERT INTO ALUMNO VALUES(3, 'HOLGA', 'ALCÁNTARA', 25, 'SISTEMAS', 9.7, 'F');
INSERT INTO ALUMNO VALUES(4, 'DANIEL', 'GARDUÑO', 45, 'LOGISTICA', 6.5, 'M');
INSERT INTO ALUMNO VALUES(5,'CASSANDRA', 'HERNANDEZ', 18, 'FINANZAS', 8.2, 'F');
INSERT INTO ALUMNO VALUES(6, 'PATRICIA', 'GONZALEZ', 24, 'MARKETING', 7.9, 'F');
INSERT INTO ALUMNO VALUES(7, 'JUAN', 'MATINEZ', 28, 'MECATRONICA', 8.9, 'M');

DELETE FROM ALUMNO;

COMMIT;

--MOSTRAR TODOS LOS ALUMNOS REGISTRADOS
SELECT * FROM ALUMNO;

--MOSTRAR EL NOMBRE Y CARRERA DE TODOS LOS ALUMNOS
SELECT NOMBRE, CARRERA FROM ALUMNO;

--MOSTRAR LOS NOMBRES Y PROMEDIOS DE LOS ALUMNOS CON PROMEDIO MAYOR A 8.0
SELECT NOMBRE, PROMEDIO FROM ALUMNO WHERE PROMEDIO >8.0;

--MOSTRAR LOS ALUMNOS QUE PERTENECEN A LA CARRERA DE SISTEMAS
SELECT * FROM ALUMNO WHERE CARRERA ='SISTEMAS';

--MOSTRAR LOS ALUMNOS CUYA EDAD SEA MAYOR O IGUAL A 22 ANIOS
SELECT * FROM ALUMNO WHERE CARRERA >= '%22';

--MOSTRAR LOS ALUMNOS ORDENADOS POR APELLIDO(A ALA Z)
SELECT *FROM ALUMNO ORDER BY EDAD ASC;
SELECT *FROM EMPLEADO ORDER BY EDAD DESC;

--MOSTRAR LOS ALUMNOS DE GENERO FEMENINO
SELECT * FROM ALUMNO WHERE GENERO = 'F';

--MOSTRAR LOS ALUMNOS ORDENADOS POR PROMEDIO (MAS BAJO A MAS ALTO)
SELECT * FROM ALUMNO ORDER BY PROMEDIO ASC;

--CONTAR CUANTOS ALUMNOS HAY EN TOTAL
SELECT COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS FROM ALUMNO;

--CONTAR CUANTOS ALUMNOS HAY POR CARRERA
SELECT CARRERA, COUNT(ID_ALUMNO) AS TOTAL_POR_CARRERA FROM ALUMNO GROUP BY CARRERA;

--MOSTRAR EL PROMEDIO GENERAL DE TODOS LOS ALUMNOS
SELECT ROUND(AVG(PROMEDIO),2) AS PROMEDIO_GENERAL FROM ALUMNO;

--MOSTRAR AL ALUMNO CON EL MEJOR PROMEDIO
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MAX(PROMEDIO) FROM ALUMNO);

--MOSTRAR AL ALUMNO CON EL PEOR PROMEDIO
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MIN(PROMEDIO) FROM ALUMNO);

--MOSTRAR LA EDAD PROMEDIO DE LOS ALUMNOS DE INFORMATICA 
SELECT ROUND(AVG(EDAD),2) AS EDAD_PROMEDIO_INFORMATICA FROM ALUMNO WHERE CARRERA = 'INFORMATICA';

--MOSTRAR CUANTOS ALUMNOS SON HOMBRES Y CUANTOS SON MUJERES
SELECT GENERO, COUNT(ID_ALUMNO) AS TOTAL FROM ALUMNO GROUP BY GENERO;

--MOSTRAR LOS ALUMNOS CUYO APELLIDO INICIE EN M
SELECT * FROM ALUMNO WHERE APELLIDO LIKE 'M%';

--DAR FORMATO CON PIPE ||
--EJE: EL ALUMNO GERARDO JIMENEZ DE EDAD 23, CURSA LA CARRERA DE SISTEMAS CON UN PROMEDIO DE 8.9
SELECT 'EL ALUMNO ' || NOMBRE || ' ' || APELLIDO ||' DE EDAD ' || EDAD ||', CURSA LA CARRERA DE ' || CARRERA ||' CON UN PROMEDIO DE ' || PROMEDIO AS DETALLE FROM ALUMNO;
