/*REALIZAR COMO PRACTICA DE BLOQUES ANONIMOS LOS SIGUIENTES EJERCICIOS
1.- CALCULAR LA SUMA DE LOS DIGITOS DE UN NUMERO 
EJEMPLO: V:=1234, SALIDA = 10. */

DECLARE
    LV_NUMERO NUMBER := 1234;
    LV_SUMA NUMBER := 0;
BEGIN
    LOOP
        LV_SUMA := LV_SUMA + MOD(LV_NUMERO,10);
        LV_NUMERO := TRUNC(LV_NUMERO/10);
        EXIT WHEN LV_NUMERO = 0;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('SUMA = ' || LV_SUMA);
END;
/


--2.- MOSTRAR LA CUENTA REGRESIVA DE 20 A 0 EN NUMEROS PARES

DECLARE
BEGIN
    FOR i IN REVERSE 0..20
    LOOP
        IF MOD(i,2)=0 THEN
            DBMS_OUTPUT.PUT_LINE('CUENTA REGRESIVA ' ||i);
        END IF;
    END LOOP;
END;
/

--3.-CALCULAR LA POTENCIA DE UN NUMERO(3^4)

DECLARE
    LV_RESULTADO NUMBER := 1;
BEGIN
    FOR i IN 1..4
    LOOP
        LV_RESULTADO:= LV_RESULTADO * 3;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('RESULTADO = ' || LV_RESULTADO);
END;
/


--4.-MOSTRAR LOS CARACTERES DE TU NOMBRE 
--'VALOR' = A
--'VALOR' = L

DECLARE
    LV_NOMBRE NVARCHAR2(20) := 'LILIANA';
BEGIN
    FOR i IN 1..LENGTH(LV_NOMBRE)
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR = ' || SUBSTR(LV_NOMBRE,i,1));
    END LOOP;
END;
/


--5.-MOSTRAR SI UN NUMERO ES PRIMO

DECLARE
    LV_NUM NUMBER := 5;
    LV_CONT NUMBER := 0;
BEGIN
    FOR i IN 1..LV_NUM
    LOOP
        IF MOD(LV_NUM,i)=0 THEN
            LV_CONT := LV_CONT +1;
        END IF;
    END LOOP;

    IF LV_CONT = 2 THEN
        DBMS_OUTPUT.PUT_LINE('ES PRIMO');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO ES PRIMO');
    END IF;
END;
/

--6.- MOSTRAR LAS TABLAS DE MILTIPLAR DEL 1 AL 10 
/*EJEMPLO TABLA DEL 1
        1 * 1 = 1
        ...
        TABLA DEL 2
*/

DECLARE
BEGIN
    FOR i IN 1..10
    LOOP
        DBMS_OUTPUT.PUT_LINE('TABLA DEL ' || i);

        FOR p IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE(i || ' * ' || p || ' = ' || (i*p));
        END LOOP;
    END LOOP;
END;
/
