--EJERCICIO: SALA Y FUNCION (CASE + JOIN)
--1.CREA LA TABLA SALA SUS CAMPOS SON ID_SALA, NOMBRE, CAPACIDAD, TIPO(1.-TRADICIONAL,2.-VIP,3.-IMAX)

CREATE TABLE SALA(
    ID_SALA NUMBER,
    NOMBRE NVARCHAR2(100),
    CAPACIDAD NUMBER,
    TIPO NUMBER, --1.TRADICIONAL, 2.VIP, 3.IMAX
    CONSTRAINT SALA_PK PRIMARY KEY(ID_SALA)
);
--2.AGREGAR POR LO MENOS 6 REGISTROS(INCLUIR ALGUNOS VALORES NULOS)

INSERT INTO SALA VALUES(1,'BETHOVEN',200,3);
INSERT INTO SALA VALUES(2,'YACHA',80,1);
INSERT INTO SALA VALUES(3,'VIVALDI',120,2);
INSERT INTO SALA VALUES(4,'CHOCHO',150,2);
INSERT INTO SALA VALUES(5,'MASERATI',NULL,1);
INSERT INTO SALA VALUES(6,'PAGANINI',60,NULL);
INSERT INTO SALA VALUES(7,'FERRS',100,NULL);

COMMIT;

SELECT *FROM SALA;


--3.CREAR LA TABLA FUNCION SUS CAMPOS SON ID_FUNCION, PELICULA, DURACION_MIN, GENERO, PRECIO_BOLETO, SALA_ID

CREATE TABLE FUNCION(
    ID_FUNCION NUMBER,
    PELICULA NVARCHAR2(100),
    DURACION_MIN NUMBER,
    GENERO NVARCHAR2(100),
    PRECIO_BOLETO NUMBER,
    SALA_ID NUMBER,
    CONSTRAINT FUNCION_PK PRIMARY KEY(ID_FUNCION),
    CONSTRAINT SALA_FK FOREIGN KEY(SALA_ID) REFERENCES SALA(ID_SALA)
);

INSERT INTO FUNCION VALUES(1,'HTTYD',195,'DRAMA',100,1);
INSERT INTO FUNCION VALUES(2,'AVATAR 3',198,'FICCION',240,3);
INSERT INTO FUNCION VALUES(3,'LA MOMIA',112,'SUSPENSO',95,2);
INSERT INTO FUNCION VALUES(4,'EL RENACER',81,'TERROR',80,4);
INSERT INTO FUNCION VALUES(5,'INTERESTELAR',169,'FICCION',160,NULL);
INSERT INTO FUNCION VALUES(6,'RAPIDOS Y FURIOSOS',140,'ACCION',130,6);
INSERT INTO FUNCION VALUES(7,'COCO',105,'INFANTIL',0,5);

COMMIT;

SELECT *FROM FUNCION;


--CONSULTAS

--1.MOSTRAR TODAS LA FUNCIONES CON EL NOMBRE DE LA SALA Y EL TIPO DE SALA USANDO CASE.
SELECT ID_FUNCION, PELICULA, NOMBRE,
(
    CASE TIPO
    WHEN 1 THEN 'TRADICIONAL'
    WHEN 2 THEN 'VIP'
    WHEN 3 THEN 'IMAX'
    ELSE 'SIN TIPO'
    END
) AS TIPO, DURACION_MIN, GENERO, PRECIO_BOLETO FROM FUNCION, SALA  WHERE SALA_ID = ID_SALA;


--2.CONTAR CUANTAS FUNCIONES HAY POR GENERO
SELECT GENERO, COUNT(ID_FUNCION) AS No_FUNCIONES
FROM FUNCION
GROUP BY GENERO;


--3.MOSTRAR LA FUNCION CON EL BOLETO MAS CARO Y AGREGAR LA PALABRA "PESOS" AL FINAL
SELECT ID_FUNCION, PELICULA, GENERO, TO_CHAR(PRECIO_BOLETO,'$999')||' PESOS' AS PRECIO_BOLETO
FROM FUNCION
WHERE PRECIO_BOLETO = (SELECT MAX(PRECIO_BOLETO) FROM FUNCION);


--4.MOSTRAR EL TOTAL DE BOLETOS QUE PODRIA VENDER CADA FUNCION(CAPACIDAD DE LA SALA * PRECIO BOLETO)
SELECT ID_FUNCION, PELICULA, CAPACIDAD, PRECIO_BOLETO,(CAPACIDAD * PRECIO_BOLETO) AS TOTAL_BOLETOS
FROM FUNCION LEFT JOIN SALA 
ON SALA_ID = ID_SALA;


--5.-MOSTRAR LA SALA CON MAYOR CAPACIDAD Y CONCATENAR EL RESULTADO CON LA PALBRA "ASIENTOS"
SELECT ID_SALA, NOMBRE,
    TO_CHAR(CAPACIDAD)||' ASIENTOS' AS CAPACIDAD
    FROM SALA
    WHERE CAPACIDAD = (SELECT MAX(CAPACIDAD) FROM SALA);


--6.MOSTRAR LAS FUNCIONES QUE NO TIENEN SALA ASIGNADA
SELECT *FROM FUNCION
WHERE SALA_ID IS NULL;


--7.ORDENAR LAS FUNCIONAS PRIMERO POR GENERO Y LUEGO POR DURACION(ES SOLO UN CONSULTA)
SELECT *FROM FUNCION
ORDER BY GENERO ASC, DURACION_MIN ASC;


--8.MOSTRAR EL DETALLE DE LAS FUNCIONES CON PIPES || "LA PELICULA TITANIC SE PROYECTA EN LA SALA VIVALDI DE TIPO VIP CON UNA DURACION DE 195 MINUTOS"
SELECT 'LA PELICULA '||PELICULA ||' SE PROYECTA EN LA SALA '||' DE TIPO '||(
            CASE TIPO
            WHEN 1 THEN 'TRADICIONAL'
            WHEN 2 THEN 'VIP'
            WHEN 3 THEN 'IMAX'
            ELSE 'SIN TIPO'
            END
       ) ||' CON UNA DURACION DE '||DURACION_MIN||' MINUTOS' AS DETALLE
FROM FUNCION 
LEFT JOIN SALA 
ON SALA_ID = ID_SALA;


--9.MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE
--9.MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE
--9.MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE

SELECT GENERO, COUNT(ID_FUNCION) AS NO_FUNCIONES
FROM FUNCION
GROUP BY GENERO
HAVING COUNT(ID_FUNCION) = (SELECT MAX(CONTADOR)
    FROM (SELECT COUNT(ID_FUNCION) AS CONTADOR
        FROM FUNCION
        GROUP BY GENERO
    )
);

