/* ACTIVIDAD DE PRACTICA DE TRIGGER
1.REALIZAR UNA TABLA ESTUDIANTE(ID,NOMBRE,APELLIDO,EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO)
2.REALIZAR LA TABLAS DE BITACORA PARA ESTUDIANTE
3.REALIZAR UNA SECUENCIA NUEVA PARA ESTUDIANTE
5.REALIZAR EL TRIGGER MULTIPLE
6.RELIZAR PRUEBAS
*/

--1.REALIZAR UNA TABLA ESTUDIANTE(ID,NOMBRE,APELLIDO,EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO)
CREATE TABLE ESTUDIANTE(
    ID_EST NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER(4,2),
    CONSTRAINT EST_PK PRIMARY KEY(ID_EST)
);


--2.REALIZAR LA TABLAS DE BITACORA PARA ESTUDIANTE
CREATE TABLE BIT_ESTUDIANTE(
    ID_BIT NUMBER,
    -- CAMPOS DE ESTUDIANTE (VALORES NUEVOS: INSERT / UPDATE)
    ID_EST NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER(4,2),
    -- VALORES VIEJOS (DELETE / UPDATE)
    NOMBRE_OLD NVARCHAR2(100),
    APELLIDO_OLD NVARCHAR2(100),
    EDAD_OLD NUMBER,
    CARRERA_OLD NVARCHAR2(100),
    CREDITOS_OLD NUMBER,
    SEMESTRE_OLD NUMBER,
    PROMEDIO_OLD NUMBER(4,2),
    -- CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_EST_PK PRIMARY KEY (ID_BIT)
);


DROP TABLE BIT_ESTUDIANTE;


--3.REALIZAR UNA SECUENCIA NUEVA PARA ESTUDIANTE
CREATE SEQUENCE S_ID_BIT_EST
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--5.REALIZAR EL TRIGGER MULTIPLE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR DATOS DE CONTROL ID POR SECUENCIA + USER + SYSDATE
    SELECT S_ID_BIT_EST.NEXTVAL, USER, SYSDATE
    INTO LV_ID_BIT, LV_USUARIO, LV_FECHA
    FROM DUAL;

    --VALIDACION DEL MOVIMIENTO
    IF INSERTING THEN
        INSERT INTO BIT_ESTUDIANTE(
            ID_BIT,
            ID_EST, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO, NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, CREDITOS_OLD, 
            SEMESTRE_OLD, PROMEDIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT,
            :NEW.ID_EST, :NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA, :NEW.CREDITOS, :NEW.SEMESTRE, :NEW.PROMEDIO,
            NULL, NULL, 0, NULL, 0, 0, 0,
            LV_USUARIO, LV_FECHA, 'INSERT'
        );
    ELSIF UPDATING THEN
        INSERT INTO BIT_ESTUDIANTE(
            ID_BIT, ID_EST, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO, NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, 
            CREDITOS_OLD, SEMESTRE_OLD, PROMEDIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT,:NEW.ID_EST, :NEW.NOMBRE, :NEW.APELLIDO, :NEW.EDAD, :NEW.CARRERA, :NEW.CREDITOS, :NEW.SEMESTRE, :NEW.PROMEDIO,
            :OLD.NOMBRE, :OLD.APELLIDO, :OLD.EDAD, :OLD.CARRERA, :OLD.CREDITOS, :OLD.SEMESTRE, :OLD.PROMEDIO, LV_USUARIO, LV_FECHA, 'UPDATE'
        );
    ELSIF DELETING THEN
        INSERT INTO BIT_ESTUDIANTE(
            ID_BIT,
            ID_EST, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO,
            NOMBRE_OLD, APELLIDO_OLD, EDAD_OLD, CARRERA_OLD, CREDITOS_OLD, SEMESTRE_OLD, PROMEDIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT, :OLD.ID_EST, NULL, NULL, 0, NULL, 0, 0, 0, :OLD.NOMBRE, :OLD.APELLIDO, :OLD.EDAD, :OLD.CARRERA, :OLD.CREDITOS, :OLD.SEMESTRE, 
            :OLD.PROMEDIO, LV_USUARIO, LV_FECHA, 'DELETE'
        );
    END IF;
END TR_MULTIPLE_ESTUDIANTE;
/



--6.RELIZAR PRUEBAS

SELECT *FROM ESTUDIANTE;

SELECT *FROM BIT_ESTUDIANTE;

--INSERTS
INSERT INTO ESTUDIANTE VALUES (1, 'LILY', 'GONZALEZ', 26, 'SISTEMAS', 220, 8, 9.50);
INSERT INTO ESTUDIANTE VALUES (2, 'SEBASTIAN', 'RAMIREZ', 27, 'QUIMICA', 180, 6, 8.80);
INSERT INTO ESTUDIANTE VALUES (3, 'RAUL', 'PEREZ', 30, 'SOFTWARE', 120, 4, 9.10);
INSERT INTO ESTUDIANTE VALUES (4, 'HOLGA', 'FLORES', 55, 'GASTRONOMIA', 170, 5, 9.30);
INSERT INTO ESTUDIANTE VALUES (5, 'SAMANTHA', 'HERNANDEZ', 61, 'MECANICA', 190, 6, 7.85);



SELECT *FROM ESTUDIANTE;
SELECT *FROM BIT_ESTUDIANTE;

--UPDATES 
UPDATE ESTUDIANTE
SET PROMEDIO = 10
WHERE ID_EST = 4;

UPDATE ESTUDIANTE
SET SEMESTRE = 7
WHERE ID_EST = 2;

UPDATE ESTUDIANTE
SET CREDITOS = 150
WHERE ID_EST = 3;

SELECT *FROM ESTUDIANTE;
SELECT *FROM BIT_ESTUDIANTE;

--DELETE
DELETE FROM ESTUDIANTE
WHERE ID_EST = 5;

SELECT *FROM ESTUDIANTE;
SELECT *FROM BIT_ESTUDIANTE;



