/*FUNCIONES PL/SQL O FUNCTION -- SON BLOQUE PL/SQL NOMBREADO
QUE RECIBE PARAMETROS DE ENTRADA (OPCIONALES)
EJECUTA UNA SERIE DE INSTRUCCIONES
DEVUELVE UN VALOR CON LA CLAUSULA RETURN
SE USAN MCUHO CUANDO QUIERES REUTILIZAR CODIGO QUE SIEMPRE RETORNE UN RESULTADO A DIFERENCIA DE UN PROCEDIMIENTO
ALMACENADO, QUE NO NECESARIAMENTE REGRESA UN RESULTADO

PUNTOS IMPORTANTE:
    RETURN TIPO_DATO -->DEFINE QUE TIPO DE VALOR REGRESA(NVARCHAR2, FECHA, NUMBER)
    SIEMPRE DEBE HABER POR LO MENOS UN RETURN EN EL BLOQUE BEGIN END
    
*/


-- CREAR UNA FUNCTION QUE ME RETORNE SI ES PAR O IMPAR UN NUMERO
CREATE OR REPLACE FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
    LV_RESULTADO NVARCHAR2(100);
BEGIN
    -- INSTRUCCIONES (VERIFICAR SI EL PARAMETRO ES DIVISIBLE ENTRE 2)
    IF MOD(P_NUMERO, 2) = 0 THEN
        LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' ES PAR';
    ELSE
        LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' ES IMPAR';
    END IF;

    RETURN LV_RESULTADO;
END FN_NUMERO_PAR;
/

--INVOCAR MEDIANTE UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(10));
END;
/

--MEDIANTE UNA CONSULTA
SELECT FN_NUMERO_PAR(31) FROM DUAL;





