--CREAR TABLA CLIENTE(ID_CLIENTE, NOMBRE, CIUDAD) AGREGAR POR LO MENOS 5 REGISTROS 

CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    CIUDAD NVARCHAR2(100),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
       
);
INSERT INTO CLIENTE VALUES(1, 'NICOLAS MORALES', 'BAJA CALIFORNIA');
INSERT INTO CLIENTE VALUES(2, 'DONATO BARRERA', 'ZACATECAS');
INSERT INTO CLIENTE VALUES(3, 'SANDRA PALMA','VERACURZ');
INSERT INTO CLIENTE VALUES(4,'PEDRO GARCIA', 'YUCATAN');
INSERT INTO CLIENTE VALUES (5,'RAMIRO JUAREZ', 'CAMPECHE');
INSERT INTO CLIENTE VALUES(6, 'OSCAR RAMIREZ', 'JALISCO');
INSERT INTO CLIENTE VALUES(7, ' JOSE PEREZ', 'MONERREY');

COMMIT;

SELECT * FROM CLIENTE;

--GENERAR LA TABLA PEDIDO (ID_PEDIDO, FECHA, MONTO, CLIENTE_ID)
CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER,
    FECHA NVARCHAR2(100),
    MONTO NUMBER,
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
       
);