--CREAR TABLA CLIENTE(ID_CLIENTE, NOMBRE, CIUDAD) AGREGAR POR LO MENOS 5 REGISTROS 

CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    CIUDAD NVARCHAR2(100),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
       
);

INSERT INTO CLIENTE VALUES(1, 'NICOLAS MORALES', 'BAJA CALIFORNIA');
INSERT INTO CLIENTE VALUES(2, 'DONATO BARRERA', 'ZACATECAS');
INSERT INTO CLIENTE VALUES(3, 'SANDRA PALMA','VERACURZ');
INSERT INTO CLIENTE VALUES(4,'PEDRO GARCIA', 'JALISCO');
INSERT INTO CLIENTE VALUES (5,'RAMIRO JUAREZ', 'CAMPECHE');
INSERT INTO CLIENTE VALUES(6, 'OSCAR RAMIREZ', 'JALISCO');
INSERT INTO CLIENTE VALUES(7, ' JOSE PEREZ', 'MONERREY');


COMMIT;

SELECT * FROM CLIENTE;

--GENERAR LA TABLA PEDIDO (ID_PEDIDO, FECHA, MONTO, CLIENTE_ID)
CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER,
    FECHA NVARCHAR2(100),
    MONTO NUMBER,
    CLIENTE_ID NUMBER,
    CONSTRAINT PEDIDO_PK PRIMARY KEY(ID_PEDIDO),
    CONSTRAINT CLIENTE_FK FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID_CLIENTE)
);

INSERT INTO PEDIDO VALUES(1, '2025-01-10', 1500, 1);
INSERT INTO PEDIDO VALUES(2, '2025-02-12', 3200, 3);
INSERT INTO PEDIDO VALUES(3, '2025-03-05', 800,  4);
INSERT INTO PEDIDO VALUES(4, '2025-03-20', 2500, 1);
INSERT INTO PEDIDO VALUES(5, '2025-04-01', 999,  6);
INSERT INTO PEDIDO VALUES(6, '2025-04-15', 1200, NULL);
INSERT INTO PEDIDO VALUES(7, '2025-05-02', 4500, NULL);

COMMIT;

SELECT * FROM PEDIDO;

--1.- MOSTRAR LOS CLIENTES QUE TIENEN PEDIDOS Y EL MONTO DE CADA PEDIDO 
--INNER JOIN
SELECT * FROM CLIENTE C
INNER JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID;

--2.- MOSTRAR TODOS LOS CLIENTES Y SUS PEDIDOS, AUNQUE NO TENGAS PEDIDOS 
--LEFT JOIN
SELECT * FROM CLIENTE C
LEFT JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID;


--3.- MOSTRAR TODOS LOS CLIENTES QUE NO TENGAN PEDIDOS 
--LEFT JOIN SIN COINCIDENCIA
SELECT * FROM CLIENTE C
LEFT JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID
WHERE P.CLIENTE_ID IS NULL;

--4.- MOSTRAR TODOS LOS PEDIDOS Y EL CLIENTE AL QUE PERTENECEN Y AUNQUE NO TENGA CLIENTE 
--RIGHT JOIN
SELECT * FROM CLIENTE C
RIGHT JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID;


--5.- MOSTRAR TODOS LOS PEDIDOS QUE NO TENGA CLIENTE 
--RIGHT JOIN SIN COINCIDENCIA
SELECT * FROM CLIENTE C
RIGHT JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID
WHERE P.CLIENTE_ID IS NULL;


--6.- MOSTRAR TODOS LOS PEDIDOS Y TODOS LOS CLIENTES (FULL JOIN)
SELECT * FROM CLIENTE C
FULL JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID;


--7.- MOSTRAR SOLO LOS PEDIDOS QUE NO TENGA CLIENTES 
--FULL JOIN SIN COINCIDENCIAS
SELECT * FROM CLIENTE C
FULL JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID
WHERE C.ID_CLIENTE IS NULL;


--8.-  TODOS LOS CLIENTES QUE NO TENGAS PEDIDOS 
--FULL JOIN SIN COINCIDENCIAS
SELECT * FROM CLIENTE C
FULL JOIN PEDIDO P
ON C.ID_CLIENTE = P.CLIENTE_ID
WHERE P.CLIENTE_ID IS NULL;