--CLAUSULA JOIN --> INNER JOIN, LETF JOIN, RIGTH JOIN, FULL JOING
--CREAR CON DDL LA IDENTIDAD DE PADRE

CREATE TABLE PADRE(
    ID_PADRE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    TRABAJO NVARCHAR2(100),
    CONSTRAINT PADRE_PK PRIMARY KEY(ID_PADRE)
       
);


INSERT INTO PADRE VALUES(1, 'NICOLAS','MORALES', 53,'DOCENTE');
INSERT INTO PADRE VALUES(2, 'DONATO', 'BARRERA', 54, 'DOCENTE');
INSERT INTO PADRE VALUES(3, 'SANDRA','PALMA', 33,'DIRECTORA');
INSERT INTO PADRE VALUES(4,'PEDRO','GARCIA',46,'PROFESOR');
INSERT INTO PADRE VALUES (5,'RAMIRO','JUAREZ',53,'DOCENTE');
INSERT INTO PADRE VALUES(6, 'OSCAR', 'RAMIREZ', 48, 'CONTADOR');
INSERT INTO PADRE VALUES(7, ' JOSE LUIS ','PEREZ', 58, 'PROFESOR');

COMMIT;

SELECT * FROM PADRE;



--GENERAR UN DDL PARA HIJO
CREATE TABLE HIJO(
    ID_HIJO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    HOBBIE NVARCHAR2(100),
    PADRE_ID NUMBER,
    CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
    CONSTRAINT PADRE_FK FOREIGN KEY(PADRE_ID)REFERENCES PADRE(ID_PADRE)
    --SE OCUPA CONSTRAINT (PALABRA RESERVADA)+NOMBRE DEL CONSTRAINT(UNICO) + TIPO DE CONSTRAINT(TIPO DE KEY) + CAMPO EN LA TABLA 
    -- QUE SERA LA LLAVE FORANEA + REFERENCE(PALABRA RESERVADA) + EL NOMBRE DE LA TABLE Y EL CAMPOAL QUE SE HACE REFERENCIA
    -- AL TABLA QUE VOY A CONECTAR EN ESTE CASO ES PADRE
);


INSERT INTO HIJO VALUES(1, 'ALINE', 'MORALES', 25, 'VER TELEVISION', 1);
INSERT INTO HIJO VALUES(2, 'JAVIER', 'CASTILLO', 12, 'JUGAR XBOX', NULL);
INSERT INTO HIJO VALUES(3, 'DANNAE', 'GARCIA', 25, 'ESCUCHAR MUSICA', 4);
INSERT INTO HIJO VALUES(4, 'DAMARIS', 'FLORES', 10, 'PINTAR', NULL);
INSERT INTO HIJO VALUES(5, ' EDUARDO', 'ANAYA ',24, 'JUGAR FUTBOL ',7);
INSERT INTO HIJO VALUES(6, 'VALERIA', 'GARCIA', 26, 'BAILAR', 3);
INSERT INTO HIJO VALUES(7,'ANGEL','GARCIA', 23, 'VOLEIBOL', 4);
INSERT INTO HIJO VALUES(8,'SOFIA','MARTINEZ', 27, 'NATACION', 6);

COMMIT;

SELECT *FROM HIJO;

--USO DE INNER JOIN --> DEVUELVE COINCIDENTES DE AMBAS TABLAS

SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;


--USO DE LEFT JOIN --> DEVULEVE TODO LOS REGISTROS DE LA TABLA IZQUIERDA(HIJO) Y LOS CALORES COINCIDENTES DE LA TABLA DERECHA(PADRE)
SELECT *FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DE LEFT JOIN SIN COINCIDENCIAS
SELECT *FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;


--USO DE RIGTH JOIN DEVULEBE TODOS LOS REGISTROS DE LA TABLA DERECHA (PADRE)
--Y LOS REGISTROS COINCIDENTES DE LA TABLA IZQUIERDA (HIJO)

SELECT *FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DE RIGHT JOIN SIN COINCIDENCIAS
SELECT *FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;


--FULL JOIN MUESTRA TODOS LOS REGISTROS DE AMBAS TABLAS Y LAS COINCIDENCIAS
SELECT *FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--FULL JOIN SIN COINCIDENCIAS
SELECT *FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;







