

--Crea un cursor que recorra todos los trabajadores y muestre su nombre y salario

SELECT *FROM TRABAJADOR;
CREATE OR REPLACE PROCEDURE PR_TRABAJADOR_NOM_SAL
IS
    -- DECLARAR CURSOR
    CURSOR CURSOR_TRABAJADOR IS
        SELECT NOMBRE, SALARIO
        FROM TRABAJADOR;
    -- VARIABLES
    LV_NOMBRE TRABAJADOR.NOMBRE%TYPE;
    LV_SALARIO TRABAJADOR.SALARIO%TYPE;

BEGIN
    -- ABRIR CURSOR
    OPEN CURSOR_TRABAJADOR;

    -- RECORRER REGISTROS
    LOOP
        FETCH CURSOR_TRABAJADOR INTO LV_NOMBRE, LV_SALARIO;
        EXIT WHEN CURSOR_TRABAJADOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE( 'EL TRABAJADOR: '||LV_NOMBRE||'  TIENE UN SALARIO DE: ' || LV_SALARIO);
    END LOOP;

    -- CERRAR CURSOR
    CLOSE CURSOR_TRABAJADOR;
END PR_TRABAJADOR_NOM_SAL;

/

BEGIN
    PR_TRABAJADOR_NOM_SAL;
END;


SELECT *FROM ESTUDIANTE;
CREATE OR REPLACE PROCEDURE PR_EST_INGENIERIA
IS
    -- DECLARAR CURSOR
    CURSOR CURSOR_EST IS
        SELECT NOMBRE, CARRERA
        FROM ESTUDIANTE
        WHERE CARRERA = 'ADMINISTRACION';

    -- VARIABLES
    LV_NOMBRE ESTUDIANTE.NOMBRE%TYPE;
    LV_CARRERA ESTUDIANTE.CARRERA%TYPE;

BEGIN
    -- ABRIR CURSOR
    OPEN CURSOR_EST;

    -- RECORRER REGISTROS
    LOOP
        FETCH CURSOR_EST INTO LV_NOMBRE, LV_CARRERA;
        EXIT WHEN CURSOR_EST%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'EL ESTUDIANTE: '||LV_NOMBRE||' ES DE LA CARRERA DE: ' || LV_CARRERA
        );
    END LOOP;

    -- CERRAR CURSOR
    CLOSE CURSOR_EST;
END PR_EST_INGENIERIA;
/

BEGIN 
    PR_EST_INGENIERIA;
END;
