/* CURSOR: ES UN MECANISMO QUE USA PL/SQL PARA RECORRER REGISTROS DE UNA CONSULTA
SQL DE FORMA FILA POR FILA

CUANDO EJECUTAS UN SELECT EN PL/SQL QUE DEVUELVE UNA SOLA FILA PUEDES USAR EL SELECT INTO
PERO SI EL SELECT DEVUELVE VARIAS FILAS, NECESITAS UN CURSOR PARA RECORRERLAS UNA A UNA

CURSORES IMPLICITOS
    SE CREAN AUTOMATICAMENTE CUANDO EJECUTAS UN INSERT, UPDATE, DELETE O SELECT INTO
    NO ES NECESARIO DECLARARLO

CURSORES EXPLICITOS
    LOS DECLARAS TU MISMO
    SE USAN PARA RECORRER RESULTADOS DE UN SELECT QUE DEVUELVE VARIAS FILAS
    TIENE 4 PASOS A SEGUIR
        DECLARAR -> ABRIR -> RECUPERAR -> CERRAR
*/


SELECT ¨FROM LIBRO;
CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
    --DECLARAR EL CURSOR
    CURSOR LIBRO_INFO IS
    SELECT NOMBRE, (
    CASE GENERO
        WHEN 1 THEN 'DRAMA'
        WHEN 2 THEN 'TERROR'
        WHEN 3 THEN 'CIENCIA FICCION'
        WHEN 4 THEN 'NOVELA'
        WHEN 5 THEN 'THRILLER'
        ELSE 'SIN GENERO'
        END) AS GENERO, PRECIO FROM LIBRO;
    --VARIABLES
    LV_NOMBRE LIBRO.NOMBRE%TYPE; --ESTA FUNCION NOS INDICA QUE LA VARIABLE DECLARADA SOLO PUEDE ALAMCENAR EL NOMBRE
    LV_GENERO NVARCHAR2(100);
    LV_PRECIO NUMBER;
BEGIN
    --2)ABRIR EL CURSOR
    OPEN LIBRO_INFO;
    
    --3)RECUPERAR EL CURSOR
    LOOP 
        --RECORER CADA FILA 
        FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
        --CONDICION SALIR CUANDO YA NO ENCUENTRE INFORMACION
        EXIT WHEN LIBRO_INFO%NOTFOUND;
        --MOSTRAR DATOS DEL CURSOR
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: '||LV_NOMBRE||', ES DE GENERO '||LV_GENERO||' Y TIENE UN PRECIO '||LV_PRECIO);
    END LOOP;
    --4)CIERRE DE CURSOR
    CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;


BEGIN
    PR_DETALLE_LIBRO;
END;

