--OPERACIONES QUE SE MANEJAN EN SQL
--DDL--> LENGUAJE PARA DEFINIR Y MODIFICAR LA ESTRUCTURA DE LLS OBJETOS EN LA BASE DE DATOS --CREATE. UPDATE--ALTER Y DROP
--DML--> LENGUAJE DE MANIPULACION DE DATOS -- SELECT. INSERT, UPDATE, DELETE
--DCL--> LENGUAJE DE CONTROL DE DATOS --> GRANT Y REVOKE

--OPERACION DE UN NUEVO USUARIO
--MODIFICAR LA SESION ACTUAL PARA LA EJECUCUON DE SCRIPTS; CUANDO SE EJECUTA UNA SENTENCIA
--QUE SIGNIFICA TENER LOS PERMISOS NECESARIOS DE ORACLE QUE SE REALICE, SE MODIFICA LA SESION Y ENTONCES PODEMOS
--EJECUTAR CUALQUIER TIPO DE OPERACION EN LA QUE SE PUEDA VER AFECTADA MI DB (LE DAMOS TODOS LOS PERMISOS)

ALTER SESSION SET "_ORACLE_SCRIPT" =TRUE; --EJECUTAR CTRL + ENTER
CREATE USER CURSOBD IDENTIFIED BY 12345;
--OTORGAR TODOS LOS PRIVILEGIOS AL NUEVO USUARIO
GRANT ALL PRIVILEGES TO CURSOBD;


