--DDL PARA CREAR LA TABLA EMPLEADO

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)

);

--CREAR VALORES NUEVOS EN MI TABLA, OPERACIONES DML
INSERT INTO EMPLEADO VALUES(1, 'FERNANDO','GOMEZ', 24,'GERENTE GENERAL','PRODUCCION');
COMMIT; --CONFRIMAMOS LOS CAMBIOS QUE ACABAMOS DE HACER, SIEMPRE QUE SEA UNA OPERACION INSERT, UPDATE, DELETE
--SE DEBE CONFIRMAR EL CAMBIO INMEDIATAMENTE USANDO COMMIT (F11)

SELECT * FROM EMPLEADO;

--EJECUTAR UN DDL PARA TERMINAR LOS REGISTROS
DELETE FROM EMPLEADO; --SOLO ELIMINA LOS REGISTROS DENTRO DE LA TABLA

-- EJECUTAR UN DML PARA EMLIMAR LA TABLA
DROP TABLE EMPLEADO; -- ELIMNA TODA LA TABLA EN LA BD


--USO DE LOS CONSTRAINT
--EJEMPLO 1 DE USO DE PRIMARY KEY
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);

--SEGUNDA FORMA

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY (ID_EMPLEADO)
);

--TERCERA FORMA
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);

SELECT * FROM EMPLEADO;

