/*FUNCIONES PL/SQL O FUNCTION -- SON BLOQUE PL/SQL NOMBREADO
QUE RECIBE PARAMETROS DE ENTRADA (OPCIONALES)
EJECUTA UNA SERIE DE INSTRUCCIONES
DEVUELVE UN VALOR CON LA CLAUSULA RETURN
*/



--FUNCION QUE RECIBA DOS NUMEROS Y RETORNE SUMA

CREATE OR REPLACE FUNCTION FN_SUM(P_NUM1 IN NUMBER, P_NUM2 IN NUMBER)
RETURN NUMBER
IS
    LV_RESULTADO NUMBER;
BEGIN
    LV_RESULTADO := P_NUM1 + P_NUM2;
    RETURN LV_RESULTADO;
END FN_SUM;
/

--INVOCAR MEDIANTE UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE(FN_SUM(4, 2));
END;
/

--MEDIANTE UNA CONSULTA
SELECT FN_SUM(4, 2) FROM DUAL;



--CALCULAR AREA DW CIRCULO COMO PARAMETRO EP RADIO
CREATE OR REPLACE FUNCTION FN_AREA_CIRCULO(P_RADIO IN NUMBER)
RETURN NUMBER
IS
    LV_AREA NUMBER;
BEGIN
    LV_AREA := (3.1416) * (P_RADIO * P_RADIO);
    RETURN LV_AREA;
END FN_AREA_CIRCULO;
/

--PRUEBA MEDIATNE CONSULTA
SELECT FN_AREA_CIRCULO(10) FROM DUAL;


--FUNCION QUE CALCULE EDAD APARTRI DE UNA FECHA
CREATE OR REPLACE FUNCTION FN_EDAD_NAC(P_FECHA_NACIMIENTO IN DATE)
RETURN NUMBER
IS
    LV_EDAD NUMBER;
BEGIN
    LV_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, P_FECHA_NACIMIENTO)/12);
    RETURN LV_EDAD;
END FN_EDAD_NAC;
/
--PRUEBA
SELECT FN_EDAD_NAC(DATE'2000-03-26') FROM DUAL;



--RECIBIR PARAMETRO DEL 1 AL 12 Y SAQUE MES CORRSPONDIENTE
CREATE OR REPLACE FUNCTION FN_MES_NOM(P_MES IN NUMBER)
RETURN NVARCHAR2
IS
    LV_MES NVARCHAR2(100);
BEGIN
    IF P_MES = 1 THEN
        LV_MES := 'ENERO';
    ELSIF P_MES = 2 THEN
        LV_MES := 'FEBRERO';
    ELSIF P_MES = 3 THEN
        LV_MES := 'MARZO';
    ELSIF P_MES = 4 THEN
        LV_MES := 'ABRIL';
    ELSIF P_MES = 5 THEN
        LV_MES := 'MAYO';
    ELSIF P_MES = 6 THEN
        LV_MES := 'JUNIO';
    ELSIF P_MES = 7 THEN
        LV_MES := 'JULIO';
    ELSIF P_MES = 8 THEN
        LV_MES := 'AGOSTO';
    ELSIF P_MES = 9 THEN
        LV_MES := 'SEPTIEMBRE';
    ELSIF P_MES = 10 THEN
        LV_MES := 'OCTUBRE';
    ELSIF P_MES = 11 THEN
        LV_MES := 'NOVIEMBRE';
    ELSIF P_MES = 12 THEN
        LV_MES := 'DICIEMBRE';
    ELSE
        LV_MES := 'MES NO VALIDO';
    END IF;

    RETURN LV_MES;
END FN_MES_NOM;
/
--PRUEBA
SELECT FN_MES_NOM(3) FROM DUAL;



