
--TABLA EQUIPOS
CREATE TABLE EQUIPOS(
NOMBRE VARCHAR2(20),
CIUDAD VARCHAR2(20),
CONFERENCIA VARCHAR2(4),
DIVISION VARCHAR2(9),
CONSTRAINT EQUIPOS_PK PRIMARY KEY(NOMBRE)
);

--TABLA JUGADORES
CREATE TABLE JUGADORES(
CODIGO NUMBER,
NOMBRE VARCHAR2(30),
PROCEDENCIA VARCHAR2(20),
ALTURA VARCHAR2(4),
PESO NUMBER,
POSICION VARCHAR2(5),
NOMBRE_EQUIPO VARCHAR2(20),
CONSTRAINT JUGADORES_PK PRIMARY KEY(CODIGO),
CONSTRAINT JUGADORES_FK FOREIGN KEY(NOMBRE_EQUIPO)
REFERENCES EQUIPOS(NOMBRE)
);


--TABLA ESTADISTICAS
CREATE TABLE ESTADISTICAS(
TEMPORADA VARCHAR2(5),
JUGADOR NUMBER,
PUNTOS_POR_PARTIDO FLOAT(126),
ASISTENCIAS_POR_PARTIDO FLOAT(126),
TAPONES_POR_PARTIDO FLOAT(126),
REBOTES_POR_PARTIDO FLOAT(126),
CONSTRAINT ESTADISTICAS_PK PRIMARY KEY(TEMPORADA,JUGADOR),
CONSTRAINT ESTADISTICAS_FK FOREIGN KEY(JUGADOR)
REFERENCES JUGADORES(CODIGO)
);


--TABLA PARTIDOS
CREATE TABLE PARTIDOS(
CODIGO NUMBER,
EQUIPO_LOCAL VARCHAR2(20),
EQUIPO_VISITANTE VARCHAR2(20),
PUNTOS_LOCAL NUMBER,
PUNTOS_VISITANTE NUMBER,
TEMPORADA VARCHAR2(5),
CONSTRAINT PARTIDOS_PK PRIMARY KEY(CODIGO),
CONSTRAINT PARTIDOS_LOC_FK FOREIGN KEY(EQUIPO_LOCAL)
REFERENCES EQUIPOS(NOMBRE),
CONSTRAINT PARTIDOS_VIS_FK FOREIGN KEY(EQUIPO_VISITANTE)
REFERENCES EQUIPOS(NOMBRE)
);


--CONSULTAS
--1.	Mostrar el nombre de todos los jugadores ordenados alfabéticamente. (Debe devolver 432 registros.) SI 432
SELECT NOMBRE 
FROM JUGADORES 
ORDER BY NOMBRE;

--2.	Mostrar el nombre de todos los equipos ordenados alfabéticamente. SON 30

SELECT NOMBRE 
FROM EQUIPOS 
ORDER BY NOMBRE;

--3.	Mostrar el nombre de los equipos del este. AQUI ME DI CUENTA QUE 'EAST' NO ES SI NO 'East' son 15
SELECT NOMBRE 
FROM EQUIPOS 
WHERE CONFERENCIA='East';


--4.	Mostrar los equipos donde su ciudad empieza por c., es c minuscula son 3
SELECT NOMBRE,CIUDAD 
FROM EQUIPOS 
WHERE LOWER(CIUDAD) LIKE 'c%';


--5.	Mostrar todos los jugadores y su equipo ordenado por nombre del equipo. (Debe devolver 432 registros) SI 432
SELECT NOMBRE,NOMBRE_EQUIPO 
FROM JUGADORES 
ORDER BY NOMBRE_EQUIPO;


--6.	Mostrar todos los jugadores del equipo «Raptors». SON 14
SELECT NOMBRE 
FROM JUGADORES 
WHERE NOMBRE_EQUIPO='Raptors';


--7 7.	Mostrar los puntos por partido de ‘Pau Gasol’.
SELECT E.TEMPORADA,E.PUNTOS_POR_PARTIDO
FROM ESTADISTICAS E JOIN JUGADORES J ON E.JUGADOR=J.CODIGO
WHERE J.NOMBRE='Pau Gasol';


--8.	Mostrar los puntos por partido de ‘Pau Gasol’ en la temporada ’04/05′.
SELECT E.TEMPORADA,E.PUNTOS_POR_PARTIDO
FROM ESTADISTICAS E JOIN JUGADORES J ON E.JUGADOR=J.CODIGO
WHERE J.NOMBRE='Pau Gasol' AND E.TEMPORADA='04/05';

--9.	Mostrar el número de puntos de cada jugador en toda su carrera. (Debe devolver 424 registros.)
SELECT J.NOMBRE,SUM(E.PUNTOS_POR_PARTIDO) PUNTOS_CARRERA
FROM JUGADORES J JOIN ESTADISTICAS E ON E.JUGADOR=J.CODIGO
GROUP BY J.NOMBRE;

--10.	Mostrar el número de jugadores de cada equipo.
SELECT NOMBRE_EQUIPO,COUNT(*) TOTAL_JUGADORES
FROM JUGADORES GROUP BY NOMBRE_EQUIPO;

--11.	Mostrar el jugador que más puntos ha realizado en toda su carrera. ES Shaquille ONeal
SELECT * FROM(
SELECT J.NOMBRE,SUM(E.PUNTOS_POR_PARTIDO) PUNTOS_CARRERA
FROM JUGADORES J JOIN ESTADISTICAS E ON E.JUGADOR=J.CODIGO
GROUP BY J.NOMBRE
ORDER BY PUNTOS_CARRERA DESC
)
WHERE ROWNUM=1;

--12.	Mostrar el nombre del equipo, conferencia y división del jugador más alto de la NBA.
SELECT E.NOMBRE,E.CONFERENCIA,E.DIVISION
FROM JUGADORES J JOIN EQUIPOS E ON E.NOMBRE=J.NOMBRE_EQUIPO
ORDER BY (TO_NUMBER(SUBSTR(J.ALTURA,1,INSTR(J.ALTURA,'-')-1))*12+
TO_NUMBER(SUBSTR(J.ALTURA,INSTR(J.ALTURA,'-')+1))) DESC
FETCH FIRST 1 ROW ONLY;

--13.	Mostrar el partido o partidos (equipo_local, equipo_visitante y diferencia) con mayor diferencia de puntos. (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_MAYOR_DIFERENCIA AS
SELECT EQUIPO_LOCAL,EQUIPO_VISITANTE,
ABS(PUNTOS_LOCAL-PUNTOS_VISITANTE) DIFERENCIA
FROM PARTIDOS;

SELECT EQUIPO_LOCAL,EQUIPO_VISITANTE,DIFERENCIA
FROM V_MAYOR_DIFERENCIA
WHERE DIFERENCIA=(SELECT MAX(DIFERENCIA) FROM V_MAYOR_DIFERENCIA);


--14.	Mostrar la media de puntos en partidos de los equipos de la división Pacific. (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_PACIFIC_PUNTOS AS
SELECT P.EQUIPO_LOCAL EQUIPO,P.PUNTOS_LOCAL PUNTOS
FROM PARTIDOS P JOIN EQUIPOS E ON E.NOMBRE=P.EQUIPO_LOCAL
WHERE E.DIVISION='Pacific'
UNION ALL
SELECT P.EQUIPO_VISITANTE,P.PUNTOS_VISITANTE
FROM PARTIDOS P JOIN EQUIPOS E ON E.NOMBRE=P.EQUIPO_VISITANTE
WHERE E.DIVISION='Pacific';

SELECT EQUIPO,AVG(PUNTOS) MEDIA_PUNTOS
FROM V_PACIFIC_PUNTOS
GROUP BY EQUIPO;


15.	Mostrar los puntos de cada equipo en los partidos, tanto de local como de visitante. Usa una vista (CREAR UNA VIEW)
CREATE OR REPLACE VIEW V_PUNTOS_EQUIPO_PARTIDO AS
SELECT CODIGO,EQUIPO_LOCAL EQUIPO,'LOCAL' TIPO,PUNTOS_LOCAL PUNTOS
FROM PARTIDOS
UNION ALL
SELECT CODIGO,EQUIPO_VISITANTE,'VISITANTE',PUNTOS_VISITANTE
FROM PARTIDOS;

SELECT * FROM V_PUNTOS_EQUIPO_PARTIDO
ORDER BY EQUIPO,CODIGO;





