--FUNCIONES DE AGREGACION
--CONSULTAS BASICAS Y FUNCIONES DE AGREAGCION

INSERT INTO EMPLEADO VALUES(1,'DANIEL','GOMEZ',26,'GERENTE DE ADMINISTRACION','ADMINISTRACION');
INSERT INTO EMPLEADO VALUES(2,'ROBERTO','FLORES',46,'GERENTE DE SISTEMAS','SISTEMAS');
INSERT INTO EMPLEADO VALUES(3, 'WILIAM', 'ALCÁNTARA', 25, 'DISEÑADOR', 'IMAGEN');
INSERT INTO EMPLEADO VALUES(4, 'DANIEL', 'GARDUÑO', 40, 'GERENTE DE LOGISTICA', 'LOGISTICA');
INSERT INTO EMPLEADO VALUES(5,'JUAN', 'HERNANDEZ', 26, 'GERENTE DE FINANZAS', 'FINANZAS');
INSERT INTO EMPLEADO VALUES(6, 'MARIO', 'GONZALEZ', 24, 'GERENTE DE MARKETING', 'PUBLICIDAD');

COMMIT; --EN DADO CASO QUE NO SE COMFIME LOS DATOS, SE PUEDE BLOQUEAR
ROLLBACK; --EN CASO DE QUE NO ES CORRECTO EL CAMBIO ENTONCES MANDO UN ROLLBACK Y REVIERTE LOS CAMBIOS

SELECT * FROM EMPLEADO;

--MODIFICAR Y CAMBIAR EL NOMBRE DE LA COMLUNA
ALTER TABLE EMPLEADO RENAME COLUMN APP TO APELLIDO;

--DML ACTUALIZAR (UPDATE)EN UN DATO DE LA TABLA
UPDATE EMPLEADO SET NOMBRE= 'JIMENA' WHERE ID_EMPLEADO =4;
COMMIT;
SELECT *FROM EMPLEADO;

--FUNCION ORDE BY
SELECT *FROM EMPLEADO ORDER BY EDAD ASC;
SELECT *FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARACTRES EN ESPECIFICO
--BUSCAR EMPLEADO QUE SU NOMBRE INICIA CON J
SELECT *FROM EMPLEADO WHERE NOMBRE LIKE 'J%';
--BUSCAR EMPLEADOS QUE SU NOMBRE CONTENGA LA LETRA R
SELECT *FROM EMPLEADO WHERE NOMBRE LIKE '%R%';
--BUSCAR EMPLEADO QUE SU NOMBRE TERMINE CON LA LETRA 0
SELECT *FROM EMPLEADO WHERE NOMBRE LIKE '%O';


--USO DE LA TABLA DUAL: ES UNA TABLA QUE NOS OFRECE Y QUE NOS PERMITE HACER OPERACIONES SIN LA NECESIDAD
-- DE TENER UNA TABLA CREADA
SELECT 5 + 5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT LENGTH ('ESTA CADENA ES UNA PRUEBA PARA EL USO DE LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADOS MAYORES DE 25
SELECT *FROM EMPLEADO WHERE EDAD >25;

--BUSCAR EMPLEADOS MENORES DE 30
SELECT *FROM EMPLEADO WHERE EDAD <30;
--BUSCAR EMPLEADOS QUE SEAN MAYORES DE 24 Y MENORES DE 28
SELECT *FROM EMPLEADO WHERE EDAD >24 AND EDAD <28;
--USAR EL RANGO BEETWEN
SELECT *FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 28;


--BUSCAR LOS EMPLEADOS CON EL ID 1 Y 5
SELECT *FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO =5;

--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,5); 

--USO DE LA FUNCION GROUP BY Y COUNT
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;

SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO GROUP BY DEPARTAMENTO;

--CONTAR LOS EMPLEADOS MAYORES A 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD >25;

--USO DE LA FUNCION SUM
SELECT SUM (EDAD) AS SUMA_EDADES FROM EMPLEADO;

--FUNCION DE AGREGACION MAX
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;

--FUNUCION MIN
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

--FUNCION AVG(AVERAGE) FUNCION DE SACAR EL PROMEDIO DE CIERTA CANTIDAD
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;

--FUNCION ROUND
SELECT ROUND (AVG(EDAD),2)AS PROMEDIO_EDAD_RENDODEADO FROM EMPLEADO;

--USO DE TO_CHAR CON FORMATO
SELECT TO_CHAR(AVG(EDAD), 'fm999.0') AS PROMEDIO_EDAD FROM EMPLEADO;

--DAR UN FORMATO DIFERENTE CONCATENAR PALABRAS
--CONCAT}
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO', ' '),NOMBRE), ' '), APELLIDO) AS DETALLE FROM EMPLEADO;

--USO DE PIPE O BARRAS VERTICALES --> ||
SELECT 'EL EMPLEADO(A) ' ||NOMBRE|| ' ' ||APELLIDO||' CON LA EDAD DE ' ||EDAD||' AÑOS, TRABAJA EN EL DEPARTAMENTO DE ' ||
DEPARTAMENTO||' COMO ' ||PUESTO AS DETALLE_EMPLEADO FROM EMPLEADO;


--SUBCONSULDAS O CONSULTAS ANIDADAS

INSERT INTO EMPLEADO VALUES(7, 'MARIA', 'HUERTA', 30, 'JEFE DE MARKETING', 'PUBLICIDAD');
COMMIT;

--BUSCAR EL EMPLEADO MAS GRANDE DEL DEAPRTAMENTO
SELECT *FROM EMPLEADO WHERE
EDAD =(
        SELECT MAX(EDAD)
        FROM EMPLEADO
        WHERE DEPARTAMENTO =('PUBLICIDAD')
);

---MAS PEQUEÑO DEL DEPTO DE PUBLICIDAD
SELECT *FROM EMPLEADO WHERE
EDAD =(
        SELECT MIN(EDAD)
        FROM EMPLEADO
        WHERE DEPARTAMENTO =('PUBLICIDAD')
);

