/*
BLOQUES PL/SQL

:BLOQUE QUE PUEDE EJECUTAR SENTENCIAS
DECLARE | IS | AS OPCIONAL, NO ES NECESARIO DEFINIR SIEMPRE LAS VARIABLES O CONSTANTES
BEGIN(INSTRUCCIONES):CONTIENE LAS SENTENCIAS QUE EL BLOQUE DEBE EJECUTAR
EXCEPCIONES: SE PUEDEN O NO CAPTURAR EXCEPCIONES DEL SISTEMA

SINTAXIS
DECLARE | IS | AS
BEGIN 
........
EXCEPTION 
END;
/ <-- INDICADOR EN EL QUE AQUI CIERRA EL BLOQUE

*/

DECLARE --DECLARACION DE VARIABLES, CONSTANTES O CURSORES
LV_VARIABLE NUMBER :=0;
BEGIN /*DONDE INICIA LA EJECUION DE SENTENCIAS*/
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO BLOQUE ANONIMO PL/SQL');
END;
/ --INDICADOR HASTA AQUI TERMINAR Y HASTA AQUI DEBE EJECUTAR

--USO DE CICLOS CON PL/SQL
DECLARE
LV_VARIABLE NUMBER :=0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE: ' || LV_VARIABLE);
        LV_VARIABLE := LV_VARIABLE +1;
        --SALIR CUANDO LA VARIABLE SEA 10
        IF LV_VARIABLE = 10
            THEN EXIT;
        END IF;
    END LOOP;
END;
/
        
--USO DEL CICLO FOR Y LOOP
DECLARE
BEGIN
    --FOR
    FOR i IN 1..10
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE LA VARIABLE FOR: ' || i);
            EXIT WHEN i = 6;
        END LOOP;
END;
/


--USO DEL CICLO WHILE Y LOOP
DECLARE
LV_ITERATOR NUMBER :=1;
BEGIN
    WHILE LV_ITERATOR <=6
    LOOP
        DBMS_OUTPUT.PUT_LINE('VALOR DEL ITERATOR CON WHILE: ' || LV_ITERATOR);
        LV_ITERATOR := LV_ITERATOR +1;
    END LOOP;
END;
/
        
--ISO DE VARIABLES BOOLEANA Y LOOP
DECLARE
LV_VALIDADOR BOOLEAN :=FALSE;
BEGIN
    FOR i IN 1..20
        LOOP
            DBMS_OUTPUT.PUT_LINE('VALOR DE KA VARIABLE: ' || i);
            IF
                i= 9 THEN 
                    LV_VALIDADOR := TRUE;
            END IF;
                EXIT WHEN LV_VALIDADOR;
        END LOOP;
END;
/


