/*PROCEDIMIENTO ALMACENADO(STORED PROCEDURE): ES UN BLOQUE DE CODIGO SQL QUE SE GUARDA
Y EJECUTA DIRECTAMENTE EN EL SERVIDOR DE LA BASDE DE DATOS, ES UNA UNIDAD REUTILIZABEL
DE PROGRAMACION QUE PUEDE REALIZAR TAREAS COMO CONSULTAS, INSERCIONES, ACTUALIZACIONES, 
VALIDACIONES Y MAS 

SIRVE PARA:
AUTOMATIZAR TAREAS, TAREAS REPETITIVAS EN LA BD COMO:
    VALIDAR DATOS ANTES DE INSERTARLOS
    ACTUALIZAR VARIAS TABLAS AL MISMO TIEMPO
    GENERAR REPORTES
    SIMPLIFICAR LA LOGICA EN LAS APLICACIONES
    MEJORAR EL RENDIMIENTO Y SEGURIDAD(PORQUE LA LOGICA SE QUEDA EN EL SERVIDOR)
    
VENTAJAS DE USAR UN PROCEDIMIENTO ALMACENADO
    NOS REDUCE EL TRAFICO ENTRE LA APLICACION Y LA BD 
    PUEDE REUTILIZAR EL CODIGO MUCHAS VECES
    MEJORAS EL CONTROL Y LA VALIDACION DE DATOS
    CENTRALIZAS LA LOGICA DE NEGOCIO
    
*/


SELECT *FROM ESTUDIANTE;
DELETE FROM ESTUDIANTE;

INSERT INTO ESTUDIANTE VALUES (1, 'LILY', 'GONZALEZ', 26, 'SISTEMAS', 220, 8, 9.50);
INSERT INTO ESTUDIANTE VALUES (2, 'SEBASTIAN', 'RAMIREZ', 27, 'QUIMICA', 180, 6, 8.80);
INSERT INTO ESTUDIANTE VALUES (3, 'MONSERRAT', 'HOGUIN', 40, 'SISTEMAS', 120, 4, 9.10);
INSERT INTO ESTUDIANTE VALUES (4, 'JIMENA', 'GARCIA', 28, 'ADMINISTRACION', 190, 3, 8.30);
INSERT INTO ESTUDIANTE VALUES (5, 'LAURA', 'HERNANDEZ', 27, 'CONTABILIDAD', 100, 5, 9.90);
INSERT INTO ESTUDIANTE VALUES (6, 'ESTEBAN', 'TORRES', 21, 'FINANZAS', 120, 2, 9.00);
INSERT INTO ESTUDIANTE VALUES (7, 'DANIEL', 'RUIZ', 24, 'FILOSOFIA', 200, 7, 9.20);
INSERT INTO ESTUDIANTE VALUES (8, 'FERNANDA', 'JIMENEZ', 29, 'GASTRONONIA', 110, 4, 8.70);
INSERT INTO ESTUDIANTE VALUES (9, 'JOSE', 'MORALES', 28, 'MECANICA', 190, 6, 8.50);
INSERT INTO ESTUDIANTE VALUES (10, 'HADA', 'BAUTISTA', 42, 'MEDICINA', 160, 3, 9.0);

COMMIT;


--REALIZAR UN REPLACE DE LA TABLA ESTUDIANTE EN OTRA TABLA
--CREAR TABLA PARA CREAR EL RESPALDO

CREATE TABLE ESTUDIANTE_PRD(
    ID_EST NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    CARRERA NVARCHAR2(100),
    CREDITOS NUMBER,
    SEMESTRE NUMBER,
    PROMEDIO NUMBER(4,2),
    CONSTRAINT EST_PRD_PK PRIMARY KEY(ID_EST)
);


CREATE OR REPLACE PROCEDURE PR_RESPALDO_ESTUDIANTE
IS
    --DECLARACION DE VARIABLES, CONSTANTE O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA ESTUDIANTE_PRD
    DELETE FROM ESTUDIANTE_PRD;

    --REALIZAR EL RESPALDO DE ESTUDIANTE EN ESTUDIANTE_PRD
    INSERT INTO ESTUDIANTE_PRD(ID_EST, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO)
    SELECT ID_EST, NOMBRE, APELLIDO, EDAD, CARRERA, CREDITOS, SEMESTRE, PROMEDIO
    FROM ESTUDIANTE;
END PR_RESPALDO_ESTUDIANTE;
/

SELECT *FROM ESTUDIANTE;
SELECT *FROM ESTUDIANTE_PRD;

--EJECUTAR EL PROCEDIMIENTO ALMACENADO
EXECUTE PR_RESPALDO_ESTUDIANTE;
