/*PROCEDIMIENTO ALMACENADO(STORED PROCEDURE): ES UN BLOQUE DE CODIGO SQL QUE SE GUARDA
Y EJECUTA DIRECTAMENTE EN EL SERVIDOR DE LA BASDE DE DATOS, ES UNA UNIDAD REUTILIZABEL
DE PROGRAMACION QUE PUEDE REALIZAR TAREAS COMO CONSULTAS, INSERCIONES, ACTUALIZACIONES, 
VALIDACIONES Y MAS 

SIRVE PARA:
AUTOMATIZAR TAREAS, TAREAS REPETITIVAS EN LA BD COMO:
    VALIDAR DATOS ANTES DE INSERTARLOS
    ACTUALIZAR VARIAS TABLAS AL MISMO TIEMPO
    GENERAR REPORTES
    SIMPLIFICAR LA LOGICA EN LAS APLICACIONES
    MEJORAR EL RENDIMIENTO Y SEGURIDAD(PORQUE LA LOGICA SE QUEDA EN EL SERVIDOR)
    
VENTAJAS DE USAR UN PROCEDIMIENTO ALMACENADO
    NOS REDUCE EL TRAFICO ENTRE LA APLICACION Y LA BD 
    PUEDE REUTILIZAR EL CODIGO MUCHAS VECES
    MEJORAS EL CONTROL Y LA VALIDACION DE DATOS
    CENTRALIZAS LA LOGICA DE NEGOCIO
    
*/

CREATE TABLE COMPUTADORA(
    ID_COMPUTADORA NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPUTADORA)
); 
DROP TABLE COMPUTADORA;
SELECT *FROM COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1, 'HP', 'Pavilion 15', 8, 'Intel Core i5', 14500);
INSERT INTO COMPUTADORA VALUES (2, 'Dell', 'Inspiron 14', 16, 'Intel Core i7', 18900);
INSERT INTO COMPUTADORA VALUES (3, 'Lenovo', 'ThinkPad E14', 8, 'AMD Ryzen 5', 16500);
INSERT INTO COMPUTADORA VALUES (4, 'Asus', 'VivoBook 15', 12, 'Intel Core i5', 15800);
INSERT INTO COMPUTADORA VALUES (5, 'Acer', 'Aspire 5', 16, 'AMD Ryzen 7', 19500);
INSERT INTO COMPUTADORA VALUES (6, 'HP', 'Envy 13', 16, 'Intel Core i7', 22000);
INSERT INTO COMPUTADORA VALUES (7, 'Dell', 'XPS 13', 16, 'Intel Core i7', 28000);
INSERT INTO COMPUTADORA VALUES (8, 'Lenovo', 'IdeaPad 3', 8, 'AMD Ryzen 3', 12000);
INSERT INTO COMPUTADORA VALUES (9, 'Asus', 'ROG Strix', 32, 'Intel Core i9', 45000);
INSERT INTO COMPUTADORA VALUES (10, 'Acer', 'Nitro 5', 16, 'AMD Ryzen 7', 25000);

INSERT INTO COMPUTADORA VALUES (11, 'HP', 'ProBook 450', 8, 'Intel Core i5', 17500);
INSERT INTO COMPUTADORA VALUES (12, 'Dell', 'Latitude 5420', 16, 'Intel Core i7', 23500);
INSERT INTO COMPUTADORA VALUES (13, 'Lenovo', 'Yoga Slim 7', 16, 'AMD Ryzen 7', 26000);
INSERT INTO COMPUTADORA VALUES (14, 'Asus', 'ZenBook 14', 16, 'Intel Core i7', 27000);
INSERT INTO COMPUTADORA VALUES (15, 'Acer', 'Swift 3', 8, 'Intel Core i5', 16000);
INSERT INTO COMPUTADORA VALUES (16, 'HP', 'Victus 16', 32, 'AMD Ryzen 9', 38000);
INSERT INTO COMPUTADORA VALUES (17, 'Dell', 'G15 Gaming', 16, 'Intel Core i7', 29000);
INSERT INTO COMPUTADORA VALUES (18, 'Lenovo', 'Legion 5', 32, 'AMD Ryzen 7', 35000);
INSERT INTO COMPUTADORA VALUES (19, 'Asus', 'TUF F15', 16, 'Intel Core i7', 26500);
INSERT INTO COMPUTADORA VALUES (20, 'Acer', 'Predator Helios', 32, 'Intel Core i9', 48000);
COMMIT;


--REALIZAR UN REPLACE DE LA TABLA COMPUTADORA EN OTRA TABLA
--CREAR TABLA PARA CREAR EL RESPALDO

CREATE TABLE COMPUTADORA(
    ID_COMPUTADORA NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPUTADORA_PK PRIMARY KEY(ID_COMPUTADORA)
);


CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
    --DECLARACION DE VARIABLES, CONSTANTE O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA COMPUTADORA_PRD
    DELETE FROM COMPUTADORA_PRD;

    --REALIZAR EL RESPALDO DE COMPUTADORA EN COMPUTADORA_PRD
    INSERT INTO COMPUTADORA_PRD(ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO
    FROM COMPUTADORA;
END PR_RESPALDO_COMPUTADORA;
/

SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

--EJECUTAR EL PROCEDIMIENTO ALMACENADO
EXECUTE PR_RESPALDO_COMPUTADORA;


--APLICAR UN DESCUENTO A TODOS LOS REGISTROS DE LA TABLA COMPUTADORA
-- EJECUTAR EL PROCEDIMIENTO
EXECUTE PR_RESPALDO_COMPUTADORA;

-- aplicar un descuento a todos los registros de la tabla computadora
CREATE OR REPLACE PROCEDURE APLICAR_DESCUENTO(P_DESCUENTO IN NUMBER) 
-- ESTE PARAMETRO ME VA A INDICAR EL % DE DESC
IS
BEGIN
    UPDATE COMPUTADORA
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100));

    -- IMPRIMIR UN MENSAJE PARA INDICAR QUE SI SE APLICO EL CAMBIO
    DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL ' || P_DESCUENTO || '% A TODAS LAS COMPUTADORA');
END APLICAR_DESCUENTO;
/

SELECT * FROM COMPUTADORA;

EXECUTE APLICAR_DESCUENTO(10);
ROLLBACK;

    

