/*PROCEDIMIENTO ALMACENADO(STORED PROCEDURE): ES UN BLOQUE DE CODIGO SQL QUE SE GUARDA
Y EJECUTA DIRECTAMENTE EN EL SERVIDOR DE LA BASDE DE DATOS, ES UNA UNIDAD REUTILIZABEL
DE PROGRAMACION QUE PUEDE REALIZAR TAREAS COMO CONSULTAS, INSERCIONES, ACTUALIZACIONES,
VALIDACIONES Y MAS

SIRVE PARA:
AUTOMATIZAR TAREAS, TAREAS REPETITIVAS EN LA BD COMO:
    VALIDAR DATOS ANTES DE INSERTARLOS
    ACTUALIZAR VARIAS TABLAS AL MISMO TIEMPO
    GENERAR REPORTES
    SIMPLIFICAR LA LOGICA EN LAS APLICACIONES
    MEJORAR EL RENDIMIENTO Y SEGURIDAD(PORQUE LA LOGICA SE QUEDA EN EL SERVIDOR)

VENTAJAS DE USAR UN PROCEDIMIENTO ALMACENADO
    NOS REDUCE EL TRAFICO ENTRE LA APLICACION Y LA BD
    PUEDE REUTILIZAR EL CODIGO MUCHAS VECES
    MEJORAS EL CONTROL Y LA VALIDACION DE DATOS
    CENTRALIZAS LA LOGICA DE NEGOCIO
*/


--TABLA MEDICAMENTO

CREATE TABLE MEDICAMENTO(
    ID_MED NUMBER,
    NOMBRE NVARCHAR2(100),
    LABORATORIO NVARCHAR2(100),
    PRECIO NUMBER(10,2),
    STOCK NUMBER,
    CONSTRAINT MED_PK PRIMARY KEY(ID_MED)
);

DROP TABLE MEDICAMENTO;
SELECT * FROM MEDICAMENTO;
DELETE FROM MEDICAMENTO;

--20 REGISTROS

INSERT INTO MEDICAMENTO VALUES (1, 'NAPROXENO 850', 'BAYER', 75.00, 70);
INSERT INTO MEDICAMENTO VALUES (2, 'RANITIDINA', 'PFIZER', 40.00, 30);
INSERT INTO MEDICAMENTO VALUES (3, 'INSULINA', 'NOVO', 410.00, 40);
INSERT INTO MEDICAMENTO VALUES (4, 'IBUPROFENO 600', 'MK', 38.00, 80);
INSERT INTO MEDICAMENTO VALUES (5, 'METFORMINA 850', 'MERCK', 95.00, 100);
INSERT INTO MEDICAMENTO VALUES (6, 'DICLOFENACO', 'MK', 42.00, 20);
INSERT INTO MEDICAMENTO VALUES (7, 'LORATADINA 10', 'BAYER', 55.00, 80);
INSERT INTO MEDICAMENTO VALUES (8, 'OMEPRAZOL 20', 'PISA', 85.00, 100);
INSERT INTO MEDICAMENTO VALUES (9, 'ATORVASTATINA 20', 'BAYER', 210.00, 85);
INSERT INTO MEDICAMENTO VALUES (10, 'SUERO ORAL', 'ELECTROLIT', 25.00, 100);
INSERT INTO MEDICAMENTO VALUES (11, 'ENALAPRIL 10', 'MERCK', 70.00, 15);
INSERT INTO MEDICAMENTO VALUES (12, 'PARACETAMOL 500', 'BAYER', 45.50, 100);
INSERT INTO MEDICAMENTO VALUES (13, 'AZITROMICINA 500', 'GAMA', 220.00, 40);
INSERT INTO MEDICAMENTO VALUES (14, 'LOSARTAN 50', 'GIAL', 85.00, 110);
INSERT INTO MEDICAMENTO VALUES (15, 'CLORFENAMINA', 'GENOMMA', 38.00, 85);
INSERT INTO MEDICAMENTO VALUES (16, 'AMOXICILINA 500', 'SANDOZ', 100.00, 100);
INSERT INTO MEDICAMENTO VALUES (17, 'KETOROLACO 10', 'PISA', 48.00, 95);
INSERT INTO MEDICAMENTO VALUES (18, 'SALBUTAMOL', 'GSK', 140.00, 55);
INSERT INTO MEDICAMENTO VALUES (19, 'VITAMINA C', 'BAYER', 80.00, 105);
INSERT INTO MEDICAMENTO VALUES (20, 'CETIRIZINA 10', 'PFIZER', 68.00, 85);

COMMIT;
SELECT * FROM MEDICAMENTO;


--PROCEDIMIENTO QUE AUMENTE EL STOCK DE UN MEDICAMENTO CUANDO LLEGA NUEVO INVENTARIO

CREATE OR REPLACE PROCEDURE AUM_STOCK(P_ID_MED IN NUMBER, P_CANTIDAD IN NUMBER)
IS
 --DECLARACION DE VARIABLES, CONSTANTE O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO ACTAULIZAMOS LA TABLA MECICAMENTO
    UPDATE MEDICAMENTO
    SET STOCK = STOCK + P_CANTIDAD
    WHERE ID_MED = P_ID_MED;
    DBMS_OUTPUT.PUT_LINE('SE AUMENTO EL STOCK DEL MEDICAMENTO ' || P_ID_MED || ' EN ' || P_CANTIDAD || ' UNIDADES');
    
END AUM_STOCK;
/

-- DESCONTAR STOCK CEUANDO SE VENDE UN MDIMAENTO
-- SI NO HAY STOCK, NO REALIZAR DESCUENTO


CREATE OR REPLACE PROCEDURE VEN_MEDICAMENTO(P_ID_MED IN NUMBER, P_CANTIDAD IN NUMBER)
IS
    --DECLARACION DE VARIABLES, CONSTANTE O CURSORES
    LV_STOCK NUMBER;
BEGIN
    SELECT STOCK INTO LV_STOCK
    FROM MEDICAMENTO
    WHERE ID_MED = P_ID_MED;

    IF LV_STOCK >= P_CANTIDAD THEN
        --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO ACTUALIZAMOS LA TABLA MECICAMENTO
        UPDATE MEDICAMENTO
        SET STOCK = STOCK - P_CANTIDAD
        WHERE ID_MED = P_ID_MED;

        DBMS_OUTPUT.PUT_LINE('VENTA EXITOSA, SE DESCONTO: ' || P_CANTIDAD || ' DEL MEDICAMENTO ' || P_ID_MED);
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO HAY STOCK SUFICIENTE DEL MEDICAMENTO ' || P_ID_MED);
    END IF;
END VEN_MEDICAMENTO;
/


-- ELIMINAR MEDICAMENTO DE LA TABLA POR ID

CREATE OR REPLACE PROCEDURE ELIMINAR_MED(P_ID_MED IN NUMBER)
IS
    --DECLARACION DE VARIABLES, CONSTANTE O CURSORES
BEGIN
    --PARA PODER REUTILIZAR ESTE PROCEDIMIENTO, PRIMERO LIMPIAMOS LA TABLA MECICAMENTO
    DELETE FROM MEDICAMENTO
    WHERE ID_MED = P_ID_MED;
    DBMS_OUTPUT.PUT_LINE('SE ELIMINO EL MEDICAMENTO CON ID ' || P_ID_MED);
    
END ELIMINAR_MED;
/

-- DESCUENTO A UN LABORATORIO ESPECIFICO


CREATE OR REPLACE PROCEDURE DESC_LAB(P_LAB IN NVARCHAR2, P_DESCUENTO IN NUMBER)
IS
BEGIN
    UPDATE MEDICAMENTO
    SET PRECIO = PRECIO - (PRECIO * (P_DESCUENTO / 100))
    WHERE LABORATORIO = P_LAB;
    DBMS_OUTPUT.PUT_LINE('SE APLICO UN DESCUENTO DEL ' || P_DESCUENTO || '% AL LABORATORIO ' || P_LAB);
END DESC_LAB;
/


--PRUEBAS

SELECT * FROM MEDICAMENTO;

--AUMENTAR STOK
EXECUTE AUM_STOCK(1, 10);

--VENDER MEDICAMNTOS
EXECUTE VEN_MEDICAMENTO(4, 40);

--DESCUENTO A LBAORATORIO
EXECUTE DESC_LAB('PFIZER', 10);

--ELIMINAR MEDICAMENTO: EJEMPLO ID 20
EXECUTE ELIMINAR_MED(19);



SELECT * FROM MEDICAMENTO;

ROLLBACK;
