/*SINTAXIS DE LA SENTENCIA CASE
--CASE CAMPO COMDICIONAL
--WHEN CONDICION1 THE RESULTADO1
--WHEN CONDICION_2 THEN RESULTDADO2
......
ELSE RESULTADO_PREDENTERMINADP
END
*/

--CREAR CON DDL LA ENTIDAD DE LIBRO
CREATE TABLE LIBRO(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER, --1DARAMA, 2TERROR, 3FICCION 4 NOVELA, 5 TRAILER
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIAL NVARCHAR2(100),
    CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);


INSERT INTO LIBRO VALUES(1, 'MIL BESOS TUYOS', 'TILLIE COLE', 4, 450, 350, 'PORRUA');
INSERT INTO LIBRO VALUES(2, 'EL ULTIMO INVITADO DE LA BODA', 'CHARLES GILMAN', 0, 500, 0, 'PLANETA');
INSERT INTO LIBRO VALUES(3, 'LOS JUEGOS DEL HAMBRE', 'SUZZANE COLLINS', 2, 350,250, 'MAVEL');
INSERT INTO LIBRO VALUES(4, 'CORALINE', 'NEIL GAIMAN', 2, 150, 300, 'SALAMANDRA');
INSERT INTO LIBRO VALUES(5,'EL CABALLERO DE LA ARMADURA OXIDADA', 'Robert Fisher', 4, 93, 350.99 , 'OBELISCO');
INSERT INTO LIBRO VALUES(6, 'EL PRINCIPITO', 'ANTONIE DE SAINT', 5, 350, 400, 'PORRUA');
INSERT INTO LIBRO VALUES(7,' FIEBRE EN LAS GRADAS ',' NICK HORNBY',4,352,299, 'ANAGRAMA ');

SELECT *FROM LIBRO;

COMMIT;


SELECT ID_LIBRO, NOMBRE, AUTOR,
(
    CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'CIENCIA FICCION'
    WHEN 4 THEN 'NOVELA'
    WHEN 5 THEN 'TRILLER'
    ELSE 'SIN GENERO'
    END
) AS GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;


--PUEDEN OCURRIR MAS CONDICIONES, CLASIFICAR LOSNELEMTNOS EN UNA TABLA
SELECT ID_LIBRO, NOMBRE, AUTOR, GENERO, NO_PAGINAS,
(
    CASE
    WHEN PRECIO >400 THEN 'ES CARO: ' ||TO_CHAR(PRECIO, '$999.0')||' PESOS'
    WHEN PRECIO <=0 THEN 'EL LIBRO ES GRATIS '
    WHEN PRECIO <=400 THEN 'ES BARATO: ' ||TO_CHAR(PRECIO, '$999.0')||' PESOS'
    
    ELSE 'PRECIO NO DEFINIDO'
    END
) AS PRECIO, EDITORIAL FROM LIBRO;






