--PRACTICA 2: CONSULTAS CASE
/*
1.- CREAR LA TABLA COMPUTADORA
ID, MARCA, RAM, ALMACENAMIENTO, PROCESADOR,
TIPO(1.ESCRITORIO,2.PORTATIL,3TABLET4.TODOENUNO),
PRECIO, FECHA_COMPRA
*/

CREATE TABLE COMPUTADORA(
    ID_COMPUTADORA NUMBER,
    MARCA NVARCHAR2(100),
    RAM NUMBER, 
    ALMACENAMIENTO NUMBER,
    PROCESADOR NVARCHAR2(100),
    TIPO NUMBER, --1.ESCRITORIO, 2.PORTATIL, 3.TABLET, 4.TODOENUNO
    PRECIO NUMBER,
    FECHA_COMPRA DATE,
    CONSTRAINT COMPUTADORA_PK PRIMARY KEY(ID_COMPUTADORA)
);

--2.-AGREGAR POR LO MENOS 7 REGISTROS 
INSERT INTO COMPUTADORA VALUES(1,'ASUS',32,128,'RYZEN 7',2,35000, TO_DATE('2024-02-01','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(2,'HP',16,512,'INTEL I7',1,27000, TO_DATE('2022-11-15','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(3,'DELL',8, 1000,'INTEL I5',2,15600, TO_DATE('2023-05-10','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(4,'SAMSUNG',6,256,'EXYNOS',3,12000, TO_DATE('2025-01-10','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(5,'APPLE',8,256,'M2',2,28000, TO_DATE('2020-08-12','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(6,'ACER',12,1000,'INTEL I5',4,15000, TO_DATE('2019-01-05','YYYY-MM-DD'));
INSERT INTO COMPUTADORA VALUES(7,'LENOVO',4,128,'SNAPDRAGON',3,9000, TO_DATE('2021-03-20','YYYY-MM-DD'));

COMMIT;

SELECT * FROM COMPUTADORA;

--1.- CLASIFICA LAS COMPUTADORAS POR CAPACIDAD DE RAM
SELECT ID_COMPUTADORA, MARCA,
(
    CASE
    WHEN RAM >= 32 THEN 'RAM MUY ALTA'
    WHEN RAM >= 16 THEN 'RAM ALTA'
    WHEN RAM >= 8 THEN 'RAM MEDIA'
    WHEN RAM >= 4 THEN 'RAM BAJA'
    ELSE 'RAM NO SIRVE'
    END
) AS RAM, ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO, FECHA_COMPRA FROM COMPUTADORA;

-- > MAYOR
-- < MENOR


--2.- CLASIFICA LAS COMPUTADORAS POR PRECIO
SELECT ID_COMPUTADORA, MARCA, RAM, ALMACENAMIENTO, PROCESADOR, TIPO, 
(
    CASE
    WHEN PRECIO > 25000 THEN 'ES MUY CARA: ' || TO_CHAR(PRECIO,'$99999') || ' PESOS'
    WHEN PRECIO <= 10000 THEN 'ES MUY BARATA'
    WHEN PRECIO <= 15000 THEN 'ES BUEN PRECIO: ' || TO_CHAR(PRECIO,'$99999') || ' PESOS'
    ELSE 'PRECIO MEDIO: ' || TO_CHAR(PRECIO,'$99999') || ' PESOS'
    END
) AS PRECIO, FECHA_COMPRA FROM COMPUTADORA;


--3.- CLASIFICA LAS COMPUTADORAS POR CAPACIDAD DE ALMACENAMIENTO
SELECT ID_COMPUTADORA, MARCA, RAM, 
(
    CASE
    WHEN ALMACENAMIENTO >= 1024 THEN 'ALMACENAMIENTO MUY ALTO (1TB O MAS)'
    WHEN ALMACENAMIENTO >= 512 THEN 'ALMACENAMIENTO ALTO'
    WHEN ALMACENAMIENTO >= 256 THEN 'ALMACENAMIENTO MEDIO'
    WHEN ALMACENAMIENTO >= 128 THEN 'ALMACENAMIENTO BAJO'
    ELSE 'NO TIENE ALMACENAMIENTO'
    END
) AS ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO, FECHA_COMPRA FROM COMPUTADORA;


--4.- MUESTRA LA INFORMACION DE LA COMPUTADORA CON SU RESPECTIVO TIPO
SELECT ID_COMPUTADORA, MARCA, RAM, ALMACENAMIENTO, PROCESADOR,
(
    CASE TIPO
    WHEN 1 THEN 'ESCRITORIO'
    WHEN 2 THEN 'PORTATIL'
    WHEN 3 THEN 'TABLET'
    WHEN 4 THEN 'TODO EN UNO'
    ELSE 'SIN TIPO'
    END
) AS TIPO, PRECIO, FECHA_COMPRA FROM COMPUTADORA;


--5.- CLASIFICA LAS COMPUTADORAS POR ANTIGUEDAD
SELECT ID_COMPUTADORA, MARCA, RAM, ALMACENAMIENTO, PROCESADOR, TIPO, PRECIO, 
(
    CASE
    WHEN FECHA_COMPRA >= ADD_MONTHS(SYSDATE, -12) THEN 'NUEVA (MENOS DE 1 AÑO)'
    WHEN FECHA_COMPRA >= ADD_MONTHS(SYSDATE, -36) THEN 'SEMI NUEVA (1 A 3 AÑOS)'
    WHEN FECHA_COMPRA >= ADD_MONTHS(SYSDATE, -60) THEN 'ANTIGUA (3 A 5 AÑOS)'
    ELSE 'MUY ANTIGUA (MAS DE 5 AÑOS)'
    END
) AS FECHA_COMPRA FROM COMPUTADORA;




