--ACATIVIDAD, REALIZAR LA NUEVA TABLA DE BITACORA DE CAMBIOS PARA ESTUDIENTE 
--Y CREAR EL TRIGGER A NIVEL SENETENCIA

--TRIGUER A NIVEL SENTENCIA(STEMENT): SE EJECUTA UNA VEZ POR SENTENCIA DML
--BITACORA QUE SOLO ME REGISTRE EL MOVIMIENTO, USUARIO, FECHA DE MOVIMIENTO
--TABLA BITACORA PARA ESTUDIANTE
CREATE TABLE BIT_EST_MOV(
    ID_BIT_MOV NUMBER,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_EST_MOV_PK PRIMARY KEY(ID_BIT_MOV)
);

--TRIGUER A NIVEL SENTENCIA (SE EJECUTA UNA VEZ POR INSERT/UPDATE/DELETE)
CREATE OR REPLACE TRIGGER TR_S_MULTIPLE_ESTUDIANTE
AFTER INSERT OR UPDATE OR DELETE ON ESTUDIANTE
--CUANDO ES UN TRIGGUER A NIVEL SENTENCIA NO SE ESCRIBE FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    --RECUPERAR DATO DEL SISTEMA Y UN ID VALIDO
    SELECT S_ID_BIT_EST.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    INSERT INTO BIT_EST_MOV(ID_BIT_MOV, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
        
END TR_S_MULTIPLE_ESTUDIANTE;
/


SELECT * FROM ESTUDIANTE;
SELECT * FROM BIT_EST_MOV;

INSERT INTO ESTUDIANTE VALUES (1, 'Lily', 'Gonzalez', 26, 'Sistemas', 120, 11, 9.6);
INSERT INTO ESTUDIANTE VALUES (2, 'Sebastian', 'Ramirez', 27, 'Quimica', 90, 6, 8.9);
INSERT INTO ESTUDIANTE VALUES (5, 'Lily', 'Gonzalez', 26, 'Sistemas', 180, 9, 7.3);
INSERT INTO ESTUDIANTE VALUES (3, 'SUSY', 'DIAZ', 30, 'FINANZAS', 10, 9, 8.3);


DELETE FROM ESTUDIANTE;

SELECT * FROM BIT_EST_MOV;


