--SENTENCIAS PARA RECUPERAR LA INFROMACION DE LOS CAMPOS DEL CONTROL(USUARIO, FECHA_MOV)
--RECUPERAR USUARIO DEL SISTEMA
SELECT USER FROM DUAL;
--RECUPERAR LA FECHA
SELECT SYSDATE FROM DUAL;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
--RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
SELECT NVL (MAX(ID_BIT),0) + 1 FROM BIT_COMPUTADORA;
