/*TRIGGERS(DISPARADORES), SON UN BLOQUE DE CODIGO QUE SE EJECUTA AUTOMATICAMENTE EN RESPUESTA DE CIERTOS EVENTOS 
EN UNA TABLA O EN UNA VISTA COMO:
    -INSERT
    -DELETE
    -UPDATE
PARA QUE SE USAN LOS TRIGUERS?
SIRVEN PARA:
    REGISTRAR AUDITORIAS (BITACORAS DE CAMBIO)
    VALIDAR REGLAS DE NEGOCIO COMPLEJAS
    MANTENER LA INTEGRIDAD DE LOS DATOS
    GENERAR VALORES AUTOMATICOS (EJEMPLO CON TIMESTAP O USUARIO QUE MODIFICO)
TIPOS DE TRIGUERS
    BEFORE:SE EJECUTA ANTES DE QUE OCURRA LA OPERACION
    AFTER: SE EJECUTA DESPUES QUE OCURRA LA OPERACION
    INSTEAD OF: SE USA EN VISTAS, REMPLAZANDO UNA OPERACION DML
NIVEL DE TRIGUER
    -ROW (POR FILA): EL TRIGUER SE ACTIVA UNA VEZ POR CADA FILA AFECTADA
    STATEMENT (POR SENTENCIA): EL TRIGER SE ACTIVA UNA SOLA VEZ POR UNA INSTRUCCION SQL SIN IMPORTAR CUANTAS FILAS SE VEAN AFECTADAS
    
VARAIBLES ESPECIALES (IDENTIFICADORES DE CORRELACION)
    SE USAN UNICAMENTE EN TRIGER FOR EACH ROW(POR FILA)
    :OLD -> REPRESENTA LOS VALORES ANTERIORES DE MODIFICAR
    :NEW -> REPRESENTA LOS VALORES NUEVOS(DESPUES DE INSERTAR O MODIFICAR) SOLOS FUNCIONAN EN TRIGUER FOR EACH ROW
    
*/

--REALIZAR UN TRIGUER TIPO AFTER FRO EACH ROW PARA REALIZAR LA AUDITORIA DE LOS EVENTOS QUE OCURREN SOBRE UNA TABLA

CREATE TABLE COMPUTADORA(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

DROP TABLE COMPUTADORA;
--GENERAR UNA TABLA PARA REGISTRAR LOS MOVIMIENTOS

CREATE TABLE BIT_COMPUTADORA(
    ID_BIT NUMBER,

    -- CAMPOS DE COMPUTADORA
    -- REPRESENTAN LOS VALORES NUEVOS (CUANDO OCURRA UN INSERT O UN UPDATE)
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,

    -- REPRESENTAN LOS VALORES VIEJOS (CUANDO OCURRE UN DELETE O UPDATE)
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NUMBER,
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,

    -- CAMPOS PARA EL CONTROL (USUARIO, FECHA Y EL TIPO DE MOVIMIENTO QUE MODIFICA LA TABLA COMPUTADORA)
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_PK PRIMARY KEY (ID_BIT)
);



--TRIGER AFTER A NIVEL FILA SIMPLE
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW --TRIGGER A NIVEL FILA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO DEL SISTEMA
    SELECT USER INTO LV_USUARIO FROM DUAL;
    --RECUPERAR LA FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;
   
    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL (MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;
    --HACEMOS ESTO, PORQUE SON VALORES QUE EL TRIGUER NO VA A MANEJAR EN AUTIMATICO Y NECESITAMOS INDICAR
    --CUALES SON LOS VALORES QUE DEBEN ESCRIBIR EN LOS CAMPOS DE CONTROL
    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD,
    PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV,MOVIMIENTO)
    VALUES(LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL, 0, NULL,
    0, LV_USUARIO, LV_FECHA, 'INSERT');
END TR_I_COMPUTADORA;
/

SELECT *FROM COMPUTADORA;
SELECT *FROM BIT_COMPUTADORA;
INSERT INTO COMPUTADORA VALUES (1, 'HP', 'PAVILON', 16, 'INTEL CORE I9 12th', 15000);
INSERT INTO COMPUTADORA VALUES (2, 'HP', 'GAMING', 32, 'AMD RYZEN 9', 32000);
INSERT INTO COMPUTADORA VALUES (3, 'MAC', 'M8', 12, 'A18', 23000);
INSERT INTO COMPUTADORA VALUES (4, 'DELL', 'INSPIRON', 12, 'INTEL PENTIUM', 10000);



--TRIGER AFTER A NIVEL FILA SIMPLE (DELETE)
CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
AFTER DELETE ON COMPUTADORA
FOR EACH ROW --TRIGGER A NIVEL FILA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO DEL SISTEMA
    SELECT USER INTO LV_USUARIO FROM DUAL;
    --RECUPERAR LA FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL (MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;

    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD,
    PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, :OLD.ID_COMPU, NULL, NULL, 0, NULL, 0,
    :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO,  LV_USUARIO, LV_FECHA, 'DELETE');
END TR_D_COMPUTADORA;
/



--TRIGER AFTER A NIVEL FILA SIMPLE (UPDATE)
CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA
FOR EACH ROW --TRIGGER A NIVEL FILA
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR USUARIO DEL SISTEMA
    SELECT USER INTO LV_USUARIO FROM DUAL;
    --RECUPERAR LA FECHA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL;

    --RECUPERAR UN ID VALIDO EN AUTOINCREMENTO
    SELECT NVL (MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA;

    INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD,
    PROCESADOR_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, 
    :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR, :OLD.PRECIO, LV_USUARIO, LV_FECHA, 'UPDATE');
END TR_U_COMPUTADORA;
/


--PRUEBA MODIFICAR 3 REGISTROS
UPDATE COMPUTADORA
SET PRECIO = 1
WHERE ID_COMPU = 1;

UPDATE COMPUTADORA
SET MODELO = 'TRABAJO'
WHERE ID_COMPU = 2;

UPDATE COMPUTADORA
SET MARCA = 'LG'
WHERE ID_COMPU = 4;

--PRUEBA DELETE 
DELETE FROM COMPUTADORA WHERE ID_COMPU = 3;


SELECT *FROM COMPUTADORA;
SELECT *FROM BIT_COMPUTADORA;







