/*SECUENCIA O SECUENCE
ES UN BLOQUE O OBJETO PL/SQL QUE GENERA NUMERO CONSECUTIVOS, SIN IMPORTAR CUANTAS VECES LO USES
O DESDE QUE TABLA
SE USA PRINCIPALMENTE PARA CREAR VALORES UNICOS DE IDENTIFICADORS (ID) POR EJEMPLO LA CLAVE PROMARIA DE UNA TABLA


*/

CREATE SEQUENCE S_ID_BIT --NOMBRE
START WITH 1 --CON QUE NUMERO INICIARA
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

--LLAMA LA SECUENCIA
SELECT S_ID_BIT.NEXTVAL FROM DUAL;




