--TRIGUER A NIVEL SENTENCIA(STEMENT): SE EJECUTA UNA VEZ POR SENTENCIA DML
--BITACORA QUE SOLO ME REGISTRE EL MOVIMIENTO, USUARIO, FECHA DE MOVIMIENTO
CREATE TABLE BIT_COMPU_MOV(
    ID_BIT_MOV NUMBER,
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_COMPU_MOV_PK PRIMARY KEY(ID_BIT_MOV)
);



--TRIGUER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_S_MULTIPLE_COMPU
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
--CUANDO ES UN TRIGGUER A NIVEL SENTENCIA NO SE ESCRIBE FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    --RECUPERAR DATO DEL SISTEMA Y UN ID VALIDO
    SELECT S_ID_BIT.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_COMPU_MOV(ID_BIT_MOV, USUARIO, FECHA_MOV, MOVIMIENTO)
            VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END TR_S_MULTIPLE_COMPU;
/

--PRUEBAS
SELECT *FROM COMPUTADORA;
SELECT *FROM BIT_COMPU_MOV;
SELECT *FROM BIT_COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1, 'HP', 'FORT', 16, 'INTEL CORE I11 12 TH', 20000);
INSERT INTO COMPUTADORA VALUES (2, 'DEL', 'KSDK', 28, 'INTEL CORE I11 12 TH', 30000);
INSERT INTO COMPUTADORA VALUES (3, 'LG', 'FJNFD', 32, 'RYZEN 9', 40000);
DELETE FROM COMPUTADORA;


        