--DESACTIVAR LOS TRIGUERS SIMPLES
ALTER TRIGGER TR_I_COMPUTADORA DISABLE;
ALTER TRIGGER TR_U_COMPUTADORA DISABLE;
ALTER TRIGGER TR_D_COMPUTADORA DISABLE;

--PARA ACTIVAR MEDIANTE SENTENCIA
ALTER TRIGGER TR_I_COMPUTADORA ENABLE;

CREATE OR REPLACE TRIGGER TR_MULTIPLE_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
-- RECUPERAR LOS DATOS (RECUPERAR EL ID MEDIANTE UNA SECUENCIA)
    SELECT S_ID_BIT.NEXTVAL, USER, SYSDATE
    INTO LV_ID_BIT, LV_USUARIO, LV_FECHA
    FROM DUAL;

    -- VALIDACION PARA CUALQUIER MOVIMIENTO QUE PUEDA OCURRIR
    IF INSERTING THEN
        INSERT INTO BIT_COMPUTADORA(
            ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO,
            MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM,
            :NEW.PROCESADOR, :NEW.PRECIO,
            NULL, NULL, 0, NULL, 0,
            LV_USUARIO, LV_FECHA, 'INSERT'
        );

    ELSIF UPDATING THEN
        INSERT INTO BIT_COMPUTADORA(
            ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO,
            MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT, :OLD.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM,
            :NEW.PROCESADOR, :NEW.PRECIO,
            :OLD.MARCA, :OLD.MODELO, :OLD.RAM,
            :OLD.PROCESADOR, :OLD.PRECIO,
            LV_USUARIO, LV_FECHA, 'UPDATE'
        );

    ELSIF DELETING THEN
        INSERT INTO BIT_COMPUTADORA(
            ID_BIT, ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO,
            MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD,
            USUARIO, FECHA_MOV, MOVIMIENTO
        )
        VALUES(
            LV_ID_BIT, :OLD.ID_COMPU, NULL, NULL, 0, NULL, 0,
            :OLD.MARCA, :OLD.MODELO, :OLD.RAM,
            :OLD.PROCESADOR, :OLD.PRECIO,
            LV_USUARIO, LV_FECHA, 'DELETE'
        );
    END IF;
END TR_MULTIPLE_COMPUTADORA;
/


       
        




