/*VISTAS O VIEWS: 
TABLA VIRTUAL  QUE SE CREA DE UNA CONSULTA SQL , NO ALMACENA DATOS
FISICAMENTE, SOLO GUARDA LA CONSULTA
CUANDO CONSULTAS UNA VISTA LA BASE DE DATOS EJECUTA EL SELECT QUE LA DEFINE

PARA QUE SIRVE:
    SIMPLIFICAR CONSULTAS COMPLEJAS
    REUTILIZAR CONSULTAS
    OCULTAR COLUMNAS SENSIBLES
    MEJORAR LA SEGURIDAD

TIPOS DE VISTA
    VISTAS SIMPLES: SE USAN PARA UNA TABLA NO TIENEN FUNIONES DE AGREGACION
    VISTAS COMPLEJAS:USAN JOIN (DOS O MAS TABLAS, USAN FUNCIONES DE AGREGACION
*/

--TABLA TRABAJADOR

CREATE TABLE TRABAJADOR(
    ID_TRABAJADOR NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO  NVARCHAR2(100),
    SALARIO NUMBER,
    CONSTRAINT TRABAJADOR_PK PRIMARY KEY(ID_TRABAJADOR)
);

SELECT * FROM TRABAJADOR;
DELETE FROM TRABAJADOR;
DROP TABLE TRABAJADOR;

INSERT INTO TRABAJADOR VALUES (1, 'LILY', 'GONZALEZ', 26, 'DESARROLLADOR', 'SISTEMAS', 21000);
INSERT INTO TRABAJADOR VALUES (2, 'SEBASTIAN', 'RAMIREZ', 27, 'BASE DE DATOS', 'SISTEMAS', 23500);
INSERT INTO TRABAJADOR VALUES (3, 'MONSERRAT', 'HOGUIN', 40, 'GERENTE', 'ADMINISTRACION', 12000);
INSERT INTO TRABAJADOR VALUES (4, 'JIMENA', 'GARCIA', 28, 'AUXILIAR', 'RECURSOS HUMANOS', 9568.50);
INSERT INTO TRABAJADOR VALUES (5, 'LAURA', 'HERNANDEZ', 31, 'CONTADOR', 'FINANZAS', 10500);
INSERT INTO TRABAJADOR VALUES (6, 'ESTEBAN', 'TORRES', 35, 'VENDEDOR', 'VENTAS', 9800);
INSERT INTO TRABAJADOR VALUES (7, 'DANIEL', 'RUIZ', 33, 'CREADORA DE CONTENIDO', 'MARKETING', 10000);

COMMIT;

SELECT * FROM TRABAJADOR;



--VISTA SOLO NOMBRE, PUESTO Y SALARIO

CREATE VIEW V_TRABAJADOR_NOMBRE_PUESTO_SALARIO AS
SELECT NOMBRE, PUESTO, SALARIO
FROM TRABAJADOR;

SELECT * FROM V_TRABAJADOR_NOMBRE_PUESTO_SALARIO;


--VISTA TRABAJADORES DE SISTEMAS


CREATE VIEW V_TRABAJADORES_SISTEMAS AS
SELECT * FROM TRABAJADOR
WHERE DEPARTAMENTO = 'SISTEMAS';

SELECT * FROM V_TRABAJADORES_SISTEMAS;


--VISTA TRABAJADORES MAYORES DE 30

CREATE VIEW V_TRABAJADOR_MAYOR_30 AS
SELECT * FROM TRABAJADOR
WHERE EDAD > 30;

SELECT * FROM V_TRABAJADOR_MAYOR_30;


--VISTA TRABAJADORES CON SUELDO MAYOR A 10000


CREATE VIEW V_TRABAJADOR_S_MAY_10000 AS
SELECT * FROM TRABAJADOR
WHERE SALARIO > 10000;

SELECT * FROM V_TRABAJADOR_S_MAY_10000;


--VISTA CATEGORIZAR SALARIO ALTO, MEDIO, BAJO

CREATE VIEW V_TRABAJADOR_CATEGORIA_SALARIO AS
SELECT ID_TRABAJADOR, NOMBRE, APELLIDO,
(CASE
    WHEN SALARIO < 10000 THEN 'EL SALARIO ES DE ' ||SALARIO|| ' ES UN SALARIO BAJO'
    WHEN SALARIO >= 10000 AND SALARIO <= 15000 THEN 'EL SALARIO ES: ' ||SALARIO|| ' ES UN SALARIO MEDIO'
    WHEN SALARIO > 15000 THEN 'EL SALARIO ES: ' ||SALARIO|| ' ES UN SALARIO ALTO'
END) AS SALARIO
FROM TRABAJADOR;

DROP VIEW V_TRABAJADOR_CATEGORIA_SALARIO;

SELECT * FROM V_TRABAJADOR_CATEGORIA_SALARIO;



