/*VISTAS O VIEWS:
TABLA VIRTUAL  QUE SE CREA DE UNA CONSULTA SQL , NO ALMACENA DATOS
FISICAMENTE, SOLO GUARDA LA CONSULTA
 CUANDO CONSULTAS UNA VISTA LA BASE DE DATOS EJECUTA EL SELECT QUE LA DEFINE

PARA QUE SIRVE:
    SIMPLIFICAR CONSULTAS COMPLEJAS
    REUTILIZAR CONSULTAS
    OCULTAR COLUMNAS SENSIBLES
    MEJORAR LA SEGURIDAD

TIPOS DE VISTA
    VISTAS SIMPLES: SE USAN PARA UNA TABLA NO TIENEN FUNIONES DE AGREGACION
    VISTAS COMPLEJAS:USAN JOIN (DOS O MAS TABLAS, USAN FUNCIONES DE AGREGACION
                    
*/

SELECT *FROM COMPUTADORA;
CREATE VIEW V_COMPUS_BARATAS AS 
SELECT ID_COMPU, MARCA, MODELO, PRECIO
FROM COMPUTADORA 
WHERE PRECIO < 15000;

--CONSULTAR O USAR LA VISTA
SELECT *FROM V_COMPUS_BARATAS;

--SELECCIONAR SOLO LA MARCA HP
CREATE VIEW V_COMPUS_MARCA AS
SELECT ID_COMPU, MARCA, MODELO, PROCESADOR FROM COMPUTADORA
WHERE MARCA = 'HP';
--LLAMA LA VISTA
SELECT *FROM V_COMPUS_MARCA;

--CLASIFICACION POR RAM
CREATE VIEW V_COMPU_CATEGORIA AS
SELECT ID_COMPU, MARCA, MODELO,
(CASE
    WHEN RAM <16 THEN 'LA RAM ES DE: ' ||RAM||' ES GAMA BAJA'
    WHEN RAM >-16 AND RAM <32 THEN 'LA RAM ES DE: ' ||RAM|| '  ES GAMA MEDIA'
    WHEN RAM =32 THEN 'LA RAM ES DE: ' ||RAM||' ES GAMA ALTA'
END) AS RAM, PROCESADOR, PRECIO FROM COMPUTADORA;

SELECT *FROM V_COMPU_CATEGORIA;







