SELECT * FROM ESTUDIANTE;

--CREAR TABLA MATERIA

CREATE TABLE MATERIA(
    ID_MAT NUMBER,
    NOMBRE_MATERIA NVARCHAR2(100),
    CREDITOS NUMBER,
    CONSTRAINT MAT_PK PRIMARY KEY(ID_MAT)
);


--CREAR TABLA CALIFICACION

CREATE TABLE CALIFICACION(
    ID_CAL NUMBER,
    ESTUDIANTE_ID NUMBER,
    MATERIA_ID NUMBER,
    CALIFICACION NUMBER,
    CONSTRAINT CAL_PK PRIMARY KEY(ID_CAL),
    CONSTRAINT CAL_EST_FK FOREIGN KEY(ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID_EST),
    CONSTRAINT CAL_MAT_FK FOREIGN KEY(MATERIA_ID) REFERENCES MATERIA(ID_MAT)
);
SELECT *FROM MATERIA;
DELETE FROM MATERIA;
DROP TABLE MATERIA;

--MATERIAS
INSERT INTO MATERIA VALUES(1, 'PROGRAMACION POO', 8);
INSERT INTO MATERIA VALUES(2, 'BASES DE DATOS', 10);
INSERT INTO MATERIA VALUES(3, 'DESARROLLO MOVIL', 7);
--INSERT INTO MATERIA VALUES(4, 'MATEMATICAS', 9);
--INSERT INTO MATERIA VALUES(5, 'ESTADISTICA', 6);
--INSERT INTO MATERIA VALUES(6, 'LEOYE', 9);

COMMIT;

SELECT *FROM CALIFICACION;
DELETE FROM CALIFICACION;



--CALIFICACIONES
--LILY
INSERT INTO CALIFICACION VALUES(1, 1, 1, 9.50);
INSERT INTO CALIFICACION VALUES(2, 1, 2, 9.00);
INSERT INTO CALIFICACION VALUES(3, 1, 3, 9.90);

--SEBASTSN
INSERT INTO CALIFICACION VALUES(4, 2, 1, 8.60);
INSERT INTO CALIFICACION VALUES(5, 2, 2, 9.90);
INSERT INTO CALIFICACION VALUES(6, 2, 4, 9.10);

--MONSE
INSERT INTO CALIFICACION VALUES(7, 3, 2, 9.90);
INSERT INTO CALIFICACION VALUES(8, 3, 3, 8.70);
INSERT INTO CALIFICACION VALUES(9, 3, 4, 9.00);

--JIMNA
INSERT INTO CALIFICACION VALUES(10, 4, 1, 9.80);
INSERT INTO CALIFICACION VALUES(11, 4, 2, 10.00);
INSERT INTO CALIFICACION VALUES(12, 4, 4, 9.50);

--LAURA
INSERT INTO CALIFICACION VALUES(13, 5, 1, 8.50);
INSERT INTO CALIFICACION VALUES(14, 5, 3, 6.00);
INSERT INTO CALIFICACION VALUES(15, 5, 4, 8.20);

--ESTEBAN
INSERT INTO CALIFICACION VALUES(16, 6, 1, 6.50);
INSERT INTO CALIFICACION VALUES(17, 6, 3, 8.00);
INSERT INTO CALIFICACION VALUES(18, 6, 4, 8.20);

SELECT *FROM CALIFICACION;
DELETE FROM CALIFICACION;

COMMIT;


--NOMBRE COMPLETO DEL ESTUDIANTE + MATERIA + CALIFICACION
CREATE OR REPLACE VIEW V_EST_MAT_CALI AS
SELECT 
    E.NOMBRE||' '||E.APELLIDO AS NOMBRE,
    M.NOMBRE_MATERIA,
    C.CALIFICACION
FROM ESTUDIANTE E
INNER JOIN CALIFICACION C
ON E.ID_EST = C.ESTUDIANTE_ID
INNER JOIN MATERIA M
ON M.ID_MAT = C.MATERIA_ID;

SELECT *FROM V_EST_MAT_CALI;


--PRIOMEDIO DE CADA ALUMNO SEGUN CALIFICACIIN
CREATE OR REPLACE VIEW V_PROM_CALIFICACION AS
SELECT
    E.ID_EST, E.NOMBRE AS NOMBRE,
    ROUND(AVG(C.CALIFICACION), 2) AS PROMEDIO
FROM ESTUDIANTE E
INNER JOIN CALIFICACION C
ON E.ID_EST = C.ESTUDIANTE_ID
GROUP BY E.ID_EST, E.NOMBRE, E.APELLIDO;

SELECT *FROM V_PROM_CALIFICACION;


--PROMDIO MATERIA
CREATE OR REPLACE VIEW V_PROMEDIO_MATERIA AS
SELECT
    M.ID_MAT,
    M.NOMBRE_MATERIA,
    ROUND(AVG(C.CALIFICACION),1) AS PROMEDIO_MATERIA
FROM MATERIA M
INNER JOIN CALIFICACION C
ON M.ID_MAT = C.MATERIA_ID
GROUP BY M.ID_MAT, M.NOMBRE_MATERIA;

SELECT *FROM V_PROMEDIO_MATERIA;



--PROMEDIO SUOERIR AL GENERAL
CREATE OR REPLACE VIEW V_EST_SUP_GEN AS
SELECT
    E.ID_EST,
    E.NOMBRE AS NOMBRE,
    ROUND(AVG(C.CALIFICACION), 2) AS PROMEDIO_ALUMNO
FROM ESTUDIANTE E
INNER JOIN CALIFICACION C
ON E.ID_EST = C.ESTUDIANTE_ID
GROUP BY E.ID_EST, E.NOMBRE, E.APELLIDO
HAVING AVG(C.CALIFICACION) > (SELECT AVG(CALIFICACION) FROM CALIFICACION);

SELECT *FROM V_EST_SUP_GEN;


--DESEMPEÑO
CREATE OR REPLACE VIEW V_DESEMPENO AS
SELECT
    E.ID_EST,
    E.NOMBRE AS NOMBRE,
    ROUND(AVG(C.CALIFICACION), 2) AS PROMEDIO_ALUMNO,
    CASE
        WHEN AVG(C.CALIFICACION) >= 9.4 THEN 'EXCELENTE'
        WHEN AVG(C.CALIFICACION) >= 8.5 THEN 'BUENO'
        ELSE 'REGULAR'
    END AS DESEMPENO
FROM ESTUDIANTE E
INNER JOIN CALIFICACION C
ON E.ID_EST = C.ESTUDIANTE_ID
GROUP BY E.ID_EST, E.NOMBRE, E.APELLIDO;

SELECT *FROM V_DESEMPENO;

